### ISSUE TITLE
Error while generating CFG with latest angr

### ISSUE THREAD

**Issue by nutim** [angr/angr#1172] opened 2018-08-14 01:33 UTC
Getting error while generating CFG with latest release.

        `cfg = proj.analyses.CFGFast()
          File "/home/sankara/.local/lib/python2.7/site-packages/angr/analyses/analysis.py", line 108, in __call__
           oself.__init__(*args, **kwargs)
            File "/home/sankara/.local/lib/python2.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 1011, in __init__
           self._analyze()
          File "/home/sankara/.local/lib/python2.7/site-packages/angr/analyses/forward_analysis.py", line 552, in _analyze
            self._analysis_core_baremetal()
            File "/home/sankara/.local/lib/python2.7/site-packages/angr/analyses/forward_analysis.py", line 677, in _analysis_core_baremetal
            self._process_job_and_get_successors(job_info)
             File "/home/sankara/.local/lib/python2.7/site-packages/angr/analyses/forward_analysis.py", line 695, in _process_job_and_get_successors
               successors = self._get_successors(job)
             File "/home/sankara/.local/lib/python2.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 1398, in _get_successors
               jobs = self._scan_block(job)
             File "/home/sankara/.local/lib/python2.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 1653, in _scan_block
               entries = self._scan_irsb(cfg_job, current_func_addr)
             File "/home/sankara/.local/lib/python2.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 1840, in _scan_irsb
               stmt_idx
             File "/home/sankara/.local/lib/python2.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 1901, in _create_jobs
               current_function_addr, stmt_idx)
             File "/home/sankara/.local/lib/python2.7/site-packages/angr/analyses/cfg/cfg_base.py", line 2051, in _indirect_jump_encountered
               resolved, resolved_targets = self._resolve_indirect_jump_timelessly(addr, irsb, func_addr, jumpkind)
             File "/home/sankara/.local/lib/python2.7/site-packages/angr/analyses/cfg/cfg_base.py", line 1994, in _resolve_indirect_jump_timelessly
    r, resolved_targets = res.resolve(self, addr, func_addr, block, jumpkind)
             File "/home/sankara/.local/lib/python2.7/site-packages/angr/analyses/cfg/indirect_jump_resolvers/mips_elf_fast.py", line 44, in resolve
               ignored_regs=('gp',)
             File "/home/sankara/.local/lib/python2.7/site-packages/angr/blade.py", line 62, in __init__
    self._backward_slice()
             File "/home/sankara/.local/lib/python2.7/site-packages/angr/blade.py", line 275, in _backward_slice
               data.get('stmt_idx', None)
             File "/home/sankara/.local/lib/python2.7/site-packages/angr/blade.py", line 347, in _backward_slice_recursive
               self._backward_slice_recursive(level - 1, pred, regs, stack_offsets, prev, data.get('stmt_idx', None))
             File "/home/sankara/.local/lib/python2.7/site-packages/angr/blade.py", line 297, in _backward_slice_recursive
               if type(exit_stmt.guard) is pyvex.IRExpr.RdTmp:
           AttributeError: 'WrTmp' object has no attribute 'guard'`

**Comment by rhelmot** [comment] 2018-08-14 22:48
Can you please upload the binary producing this behavior? I can't reproduce it on any of my samples.

**Comment by nutim** [comment] 2018-08-15 04:04
I am playing around with too many binaries. will send you soon.

**Comment by mephi42** [comment] 2018-09-28 16:27
I just ran into this too, and apparently it's because of `IRSB._from_c` computing `_exit_statements` before `ZeroDivisionPostProcessor` runs and leaving inconsistent `exit_stmt_idx` in `CFGFast` edge's `data`.

Unfortunately I cannot share the binary, but the problematic insn is AMD64 `vdivsd %xmm9,%xmm14,%xmm15`.

**Comment by mephi42** [comment] 2018-09-28 18:38
Must be a bit more complicated, since `ZeroDivisionPostProcessor` has an explicit protection against that. Anyway, good news: here is the minimal example:

```
	.globl	main
main:
	vdivsd %xmm9,%xmm14,%xmm15
	je main
	jmp *table(,%rax,8)
table:
	.quad main
```

**Comment by rhelmot** [comment] 2018-09-28 20:08
```
In [13]: pyvex.lift(b, 0, arch, skip_stmts=True).exit_statements
Out[13]: ((5, 14, <pyvex.stmt.Exit at 0x7fbfc97a3af8>),)

In [14]: pyvex.lift(b, 0, arch, skip_stmts=False).exit_statements
Out[14]: 
((0, 4, <pyvex.stmt.Exit at 0x7fbfcaaea870>),
 (5, 16, <pyvex.stmt.Exit at 0x7fbfca04a9d8>))
```

that'll do it :/

**Comment by rhelmot** [comment] 2018-09-28 20:09
So basically it looks like if we're going to be depending on exit_statements we absolutely cannot write postprocessors in python anymore. great

**Comment by ltfish** [comment] 2018-09-29 17:13
> we absolutely cannot write postprocessors in python anymore

I believe your post-processor can require statements, which will cause a re-lifting with `skip_stmts=False`.

**Comment by ltfish** [comment] 2018-09-29 18:14
(After a long and heated discussion with @rhelmot on Slack) It seems that the root problem is sharing a piece of volatile information -- in this case, statement IDs in basic blocks -- across different runs of block lifting and expecting it to stay consistent.

Here is the proposed solution:

- We treat statement IDs as "volatile" information. if users use it across lifting runs, they are responsible for themselves.
- We introduce consistent exit IDs that do not change. if a post-processor introduces new exits, they will have to have unique IDs.
- We keep Python postprocessors.
- We provide a way to enable/disable all _optional_ postprocessors (for example, the ZeroDivisionPostProcessor).

**Comment by rhelmot** [comment] 2018-10-01 11:13
https://github.com/angr/pyvex/commit/74607c0b3ca187163bf744b53604ad1ce0e875dd

As a stopgap, I rewrote the zero division post processor in C. Thanks! This commit has been released in the new angr 8 release.

**Closed by rhelmot** 2018-10-01 11:13 UTC
Labels: bug
