### ISSUE TITLE
AILBlockSimplifier insufficiently leaves assignments to temps in some circumstances

### ISSUE THREAD

**Issue by fmagin** [angr/angr#2789] opened 2021-06-30 13:23 UTC
**Describe the bug.**
On a certain basic block the `AILBlockSimplifier` doesn't fully simplify away the assignments to temporary registers.

**Environment Information.**

```
angr environment report
=============================
Date: 2021-06-30 15:22:38.818117
Running in virtual environment at /home/fmagin/.virtualenvs/sit-angr-analysis-service
Platform: linux-x86_64
Python version: 3.9.5 (default, May 24 2021, 12:50:35) 
[GCC 11.1.0]
######## angr #########
Python found it in /home/fmagin/Projects/angr-dev/angr/angr
Pip version angr 9.0.gitrolling
Git info:
	Current commit c0555f2180105eb2b2626a2be5361dcacbbc04c0 from branch ail_simplification
Could not resolve tracking branch or remote info!
######## ailment #########
Python found it in /home/fmagin/Projects/angr-dev/ailment/ailment
Pip version ailment 9.0.gitrolling
Git info:
	Current commit 9c3abc9a226f2f3fdca5f56a22d8bd694d2035b4 from branch master
	Checked out from remote origin: https://github.com/angr/ailment.git
######## cle #########
Python found it in /home/fmagin/Projects/angr-dev/cle/cle
Pip version cle 9.0.gitrolling
Git info:
	Current commit cde3d3639a6f0236a3197ccee9762f8b021d0935 from branch repr_fix
	Checked out from remote fmagin: git@github.com:fmagin/cle.git
######## pyvex #########
Python found it in /home/fmagin/Projects/angr-dev/pyvex/pyvex
Pip version pyvex 9.0.gitrolling
Git info:
	Current commit b7006517fcb9fcd713b070315b7c18277c942113 from branch master
	Checked out from remote origin: https://github.com/angr/pyvex.git
######## claripy #########
Python found it in /home/fmagin/Projects/angr-dev/claripy/claripy
Pip version claripy 9.0.gitrolling
Git info:
	Current commit d372dd28bede388d44c018b06168239ca335329a from branch master
	Checked out from remote origin: https://github.com/angr/claripy.git
######## archinfo #########
Python found it in /home/fmagin/Projects/angr-dev/archinfo/archinfo
Pip version archinfo 9.0.gitrolling
Git info:
	Current commit b150db4c0a939140966df8b0056b6deb5b07efbf from branch master
	Checked out from remote origin: https://github.com/angr/archinfo.git
######## z3 #########
Python found it in /home/fmagin/.virtualenvs/sit-angr-analysis-service/lib/python3.9/site-packages/z3
Pip version z3-solver 4.8.10.0
Couldn't find git info
######## unicorn #########
Python found it in /home/fmagin/.virtualenvs/sit-angr-analysis-service/lib/python3.9/site-packages/unicorn
Pip version unicorn 1.0.2rc4
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/fmagin/Projects/angr-dev/angr/angr/lib/angr_native.so', handle 5615d2a9eb90 at 0x7f5705d69250>
unicorn: <CDLL '/home/fmagin/.virtualenvs/sit-angr-analysis-service/lib/python3.9/site-packages/unicorn/lib/libunicorn.so', handle 5615d2184080 at 0x7f570b5c1b80>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f570c194f70>
z3: <CDLL '/home/fmagin/.virtualenvs/sit-angr-analysis-service/lib/python3.9/site-packages/z3/lib/libz3.so', handle 5615d23b5590 at 0x7f570918a610>
```

**To Reproduce.**
```python
import os

import ailment
import angr
# Dummy project so analyses work properly
p = angr.Project(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                              '..', '..', 'binaries', 'tests', 'armhf', 'dummy.macho'), auto_load_libs=False)
basic_block = p.factory.block(addr=0x100008888,
                              byte_string=b'\xf6W\xbd\xa9'  # 0x100008888:	stp	x22, x21, [sp, #-0x30]!
                                          b'\xf4O\x01\xa9'  # 0x10000888c:	stp	x20, x19, [sp, #0x10]
                                          b'\xfd{\x02\xa9'  # 0x100008890:	stp	x29, x30, [sp, #0x20]
                                          b'\xfd\x83\x00\x91'  # 0x100008894:	add	x29, sp, #0x20
                                          b'\xf3\x03\x00\xaa'  # 0x100008898:	mov	x19, x0
                                          b'\x08\x08B\xa9'  # 0x10000889c:	ldp	x8, x2, [x0, #0x20]
                                          b'\x00\x05@\xf9'  # 0x1000088a0:	ldr	x0, [x8, #8]
                                          b'c\x1a@\xf9'  # 0x1000088a4:	ldr	x3, [x19, #0x30]
                                          b'\xe8U\x00\xf0'  # 0x1000088a8:	adrp	x8, #0x100ac7000
                                          b'\x01!E\xf9'  # 0x1000088ac:	ldr	x1, [x8, #0xa40]
                                          b'\xbe\xa6\x1c\x94'  # 0x1000088b0:	bl	#0x1007323a8
                              )
ailMgr = ailment.Manager(arch=p.arch)
lifted_block = ailment.IRSBConverter.convert(basic_block.vex, ailMgr)
lifted_result = p.analyses.AILBlockSimplifier(lifted_block)

# All assignments should be to registers, and not temp variables
for stmt in lifted_result.result_block.statements:
    if isinstance(stmt, ailment.Assignment):
        assert not isinstance(stmt.dst, ailment.Tmp)
```

@ltfish

**Comment by rhelmot** [comment] 2021-06-30 19:17
Probably a duplicate of https://github.com/angr/angr-management/issues/350? tldr the simplifier is currently incapable of reasoning about temps; any time temps are currently removed is a result of the lifting into variables.

**Comment by fmagin** [comment] 2021-06-30 22:19
Nope, in most cases the result of AILBlockSimplifier does not have any assignments to temps left. I already talked to @ltfish earlier today because I wasn't sure if this counted as a bug, and they considered it one.

**Comment by fmagin** [comment] 2022-06-27 08:02
@rhelmot
I just reran the PoC I posted and it doesn't fail for me anymore, so I guess we can consider this closed/fixed? Not sure if you have other evidence, because you explicitly removed the stale lavel

**Closed** 2022-06-28 04:34 UTC
