### ISSUE TITLE
lift instruction bx pc

### ISSUE THREAD

**Issue by valour01** [angr/angr#890] opened 2018-03-03 09:09 UTC
It seems that angr could not lift the instruction `bx pc`, In hexdecimal, `4778`. Could you please check this. Besides, how do angr exchange between arm mode and thumb mode. If angr doesn't support the `bx` jump, then I can do the extension by myself. Many Thanks

**Comment by rhelmot** [comment] 2018-03-03 21:24
Hi, it looks like you're trying to lift a thumb instruction. If you're trying to analyze thumb code you need to use odd addresses, i.e. one greater than the actual value, since that's how valgrind represents thumb mode. see the entry "Why are some ARM addresses off-by-one?" in our [FAQ](https://docs.angr.io/docs/faq.html).

**Comment by valour01** [comment] 2018-03-04 12:14
Sorry for the late reply. I will try to see the FAQ first. However, I need to mention that arm will exchange the arm mode and thumb mode during the running time. The `bx pc` could not be recognized during the process when I am going to create a `CFGFast` 

Besides, I found that angr doesn't support `STMFD`, either. For example,`e94d7fff`; SInce I am analyzing some bootloader and I found there are many commands that angr doesn't support, which could influence the result of CFGAccurate. Suppose I have a elf file, any suggestions on a quick scan to found out all the instructions and their corresponding addresses  that angr doesn't support.

**Comment by ltfish** [comment] 2018-03-04 13:05
It's easy to add support to `CFGFast` so that it supports `bx pc` in ARM. Where do you see such an instruction? A sample binary would be very helpful.

**Comment by valour01** [comment] 2018-03-04 13:18
@ltfish  I am so sorry that I could not release the binary due to the security policy of our company. However, I would like to give you more information so that you could give me some help. When I use CFGFast to create the target cfg, the exception is like below:

```
DEBUG   | 2018-03-04 21:13:45,774 | angr.analyses.cfg.cfg_fast | ... got 1 jobs: [<CFGJob 0x2a021ef0 @ func 0x2a021eed>]
DEBUG   | 2018-03-04 21:13:45,774 | angr.analyses.cfg.cfg_fast | Tracing new exit 0x2a021ee4 in function 0x2a021ee4
None
DEBUG   | 2018-03-04 21:13:45,774 | angr.engines.vex.engine | Creating pyvex.IRSB of arch ARMEL at 0x2a021ee4
[[pyvex_c]]	DEBUG:	Guest arch: 1027
[[pyvex_c]]	DEBUG:	Guest arch hwcaps: 00010107
DEBUG   | 2018-03-04 21:13:45,774 | pyvex.lift.libvex | Lifting extended block
DEBUG   | 2018-03-04 21:13:45,774 | pyvex.lift.libvex | Block very short
DEBUG   | 2018-03-04 21:13:45,774 | pyvex.lift.libvex | raising lifting exception
DEBUG   | 2018-03-04 21:13:45,774 | pyvex.lift | Lifting Exception: libvex: could not decode any instructions
DEBUG   | 2018-03-04 21:13:45,774 | pyvex.lift.util.lifter_helper | '\x10\x0f0\xee\x1e\xff/\xe1x'
DEBUG   | 2018-03-04 21:13:45,774 | pyvex.lift.util.lifter_helper | Starting block at address: 0x2a021ee4
ERROR   | 2018-03-04 21:13:45,775 | pyvex.lift.util.lifter_helper | Error decoding block:

Traceback (most recent call last):
  File "/home/linux/angr-dev/pyvex/pyvex/lift/util/lifter_helper.py", line 59, in decode
    raise e
ReadError: Reading off the end of the data. Tried to read 32 bits when only 8 available.
Traceback (most recent call last):
  File "cfg.py", line 180, in <module>
    cfg = p.analyses.CFG()
  File "/home/linux/angr-dev/angr/angr/analyses/analysis.py", line 96, in make_analysis
    oself.__init__(*args, **kwargs)
  File "/home/linux/angr-dev/angr/angr/analyses/cfg/cfg.py", line 58, in __init__
    CFGFast.__init__(self, **kwargs)
  File "/home/linux/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 819, in __init__
    self._analyze()
  File "/home/linux/angr-dev/angr/angr/analyses/forward_analysis.py", line 508, in _analyze
    self._analysis_core_baremetal()
  File "/home/linux/angr-dev/angr/angr/analyses/forward_analysis.py", line 633, in _analysis_core_baremetal
    self._process_job_and_get_successors(job_info)
  File "/home/linux/angr-dev/angr/angr/analyses/forward_analysis.py", line 651, in _process_job_and_get_successors
    successors = self._get_successors(job)
  File "/home/linux/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1210, in _get_successors
    jobs = self._scan_block(addr, current_function_addr, jumpkind, src_node, src_ins_addr, src_stmt_idx)
  File "/home/linux/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1484, in _scan_block
    previous_src_ins_addr, previous_src_stmt_idx)
  File "/home/linux/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1589, in _scan_irsb
    addr, function_addr, cfg_node, irsb = self._generate_cfgnode(addr, current_function_addr)
  File "/home/linux/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 3341, in _generate_cfgnode
    irsb = lifted_block.vex
  File "/home/linux/angr-dev/angr/angr/block.py", line 149, in vex
    arch=self.arch,
  File "/home/linux/angr-dev/angr/angr/engines/vex/engine.py", line 474, in lift
    opt_level=opt_level)
  File "/home/linux/angr-dev/pyvex/pyvex/block.py", line 87, in __init__
    lift(self, arch, mem_addr, data, max_bytes, max_inst, bytes_offset, opt_level, traceflags)
  File "/home/linux/angr-dev/pyvex/pyvex/lift/__init__.py", line 167, in lift
    next_irsb_part = lifter(arch, addr)._lift(u_data, bytes_offset, max_bytes, max_inst, opt_level, traceflags, allow_lookback)
  File "/home/linux/angr-dev/pyvex/pyvex/lift/__init__.py", line 67, in _lift
    self.lift()
  File "/home/linux/angr-dev/pyvex/pyvex/lift/util/lifter_helper.py", line 79, in lift
    instructions = self.decode()
  File "/home/linux/angr-dev/pyvex/pyvex/lift/util/lifter_helper.py", line 74, in decode
    raise e
bitstring.ReadError: Reading off the end of the data. Tried to read 32 bits when only 8 available.

```

Then I checked the address and try to use the `p.factory.block(2a021ee4)` to trigger the process for IR translating. And it fails on the instruction `bx pc`. The corresponding hex in IDA-Pro is `78 47 c0 46`. It seems that `c0 46` is the padding part, which has no meaning.

**Comment by rhelmot** [comment] 2018-03-04 21:00
Again: if you want to analyze thumb code, you need to use odd addresses. Try p.factory.block(0x2a021ee5).

angr completely supports `bx pc`:

```
In [8]: pyvex.IRSB('\x78\x47', 0x1001, archinfo.ArchARM(), bytes_offset=1).pp()
IRSB {
   t0:Ity_I32 t1:Ity_I32 t2:Ity_I32 t3:Ity_I32 t4:Ity_I32 t5:Ity_I32 t6:Ity_I32 t7:Ity_I32 t8:Ity_I32 t9:Ity_I32 t10:Ity_I32 t11:Ity_I32 t12:Ity_I32 t13:Ity_I32 t14:Ity_I32 t15:Ity_I32 t16:Ity_I32 t17:Ity_I1 t18:Ity_I32 t19:Ity_I32 t20:Ity_I32 t21:Ity_I1 t22:Ity_I1 t23:Ity_I1 t24:Ity_I32

   00 | ------ IMark(0x1000, 2, 1) ------
   01 | t0 = GET:I32(itstate)
   02 | t1 = Shr32(t0,0x08)
   03 | t10 = And32(t0,0x000000f0)
   04 | t9 = Xor32(t10,0x000000e0)
   05 | t11 = GET:I32(cc_op)
   06 | t8 = Or32(t11,t9)
   07 | t12 = GET:I32(cc_dep1)
   08 | t13 = GET:I32(cc_dep2)
   09 | t14 = GET:I32(cc_ndep)
   10 | t15 = armg_calculate_condition(t8,t12,t13,t14):Ity_I32
   11 | t17 = CmpNE32(t10,0x00000000)
   12 | t16 = ITE(t17,t15,0x00000001)
   13 | PUT(itstate) = t0
   14 | t21 = CmpNE32(t1,0x00000000)
   15 | if (t21) { PUT(ip) = 0x1001; Ijk_NoDecode }
   16 | PUT(itstate) = t1
   17 | t23 = 32to1(t16)
   18 | t22 = Not1(t23)
   19 | if (t22) { PUT(ip) = 0x1003; Ijk_Boring }
   NEXT: PUT(pc) = 0x00001004; Ijk_Boring
}
```

**Comment by rhelmot** [comment] 2018-03-04 21:01
fish, that does look like a real bug though. Should pyvex just be catching the bitstring error and reraising it as a pyvex error?

**Comment by ltfish** [comment] 2018-03-04 21:04
I have no clue - without an example to reproduce this issue, I have no insight about what the bug is.

My guess is a) CFGFast does not automatically switch to THUMB mode when coming across `bx pc`, which is something I can fix, and b) CFGFast tries to lift that instruction in ARM mode, and triggers another bug (the bitstring one) in PyVEX.

Again, without an example to reproduce, there is no one I can help.

@valour01 I totally understand that you cannot take the binary from your workplace and post it here. Can you please make another binary that triggers this bug?

**Comment by valour01** [comment] 2018-03-11 05:10
@ltfish @rhelmot Sorry for the late reply. I am preparing the sample binary if you still need. However, I guess I've found where the problem is. No question that angr support `bx pc`. The exception comes from the padding code. To align the code, the binary at addr `2a021ee4` is `78 47 c0 46` while `c0 46` is for padding. Thus, angr will read the `46 c0 47 78` due to the little-endian.

To solve this problem, I think I need to extend the vex to support `46 c0`. I use the following code to patch it. However, it seems not work. Is the instruction extension right? 

```
class Instruction_Code(Instruction):
   bin_format = '1100000001000110'
   name = "Code"

   def compute_result(self):
       print(self.data)
       print("We locate the Instruction Code")
```

Besides, I am still curious about how to locate all the instruction that angr(vex) doesn't support. Hope to get some suggestions from you. Many Many Thanks

**Comment by rhelmot** [comment] 2018-03-11 22:05
You are misunderstanding how ARM works. This is in thumb mode, where instructions can be only 16 bits long. Any program that tells you that the instruction bytes are `78 47 c0 46` is wrong. angr will not try to interpret this as an instruction either, our instruction decoding is done by libvex from the valgrind project. It will interpret `78 47` as bx pc, and then end the block. At least, I hope so. Your fix will definitely not work because nobody is trying to interpret `c0 48` as an instruction.

I don't know how to help you debug this. If you can provide any sort of testcase demonstrating this behavior, then I will be able to.

**Comment by valour01** [comment] 2018-04-02 16:25
Hi, sorry for the late reply. This problem doesn't occur in CFGAccurate but only in CFGFast. I am not so good at C and assembly, thus, it may cost me some time to try to generate some testcase. And also, I try to understand CFGAccurate deeply first. I hope this issue will not be closed. I will post my example later. However, this is not the first priority for me.... Hope you guys could understand my condition. Anyway, thank you so much @rhelmot @ltfish .

**Comment by bennofs** [comment] 2018-04-04 00:03
The pyvex exception may be caused by an ARM spotter. In should be fixed bu https://github.com/angr/pyvex/commit/c4e9c9e813e6f80a149a5c43534444c4b13b407c

**Comment by ArtemShypotilov** [comment] 2018-07-11 09:32
Guys, I also have some case, when "bx pc" causes problem. Here, check this code from IDA:
```
.plt:00011BF4                 CODE16
.plt:00011BF4
.plt:00011BF4 ; =============== S U B R O U T I N E =======================================
.plt:00011BF4
.plt:00011BF4 ; Attributes: thunk
.plt:00011BF4
.plt:00011BF4 ; void j_free(void *ptr)
.plt:00011BF4 j_free                                  ; CODE XREF: sub_2DFDC+2↓j
.plt:00011BF4                 BX              PC
.plt:00011BF4 ; ---------------------------------------------------------------------------
.plt:00011BF6                 ALIGN 4
.plt:00011BF6 ; End of function j_free
.plt:00011BF6
.plt:00011BF8                 CODE32
.plt:00011BF8
.plt:00011BF8 ; =============== S U B R O U T I N E =======================================
.plt:00011BF8
.plt:00011BF8 ; Attributes: thunk
.plt:00011BF8
.plt:00011BF8 ; void free(void *ptr)
.plt:00011BF8 free                                    ; CODE XREF: j_free↑j
.plt:00011BF8                 ADR             R12, 0x11C00
.plt:00011BFC                 ADD             R12, R12, #0x35000
.plt:00011C00                 LDR             PC, [R12,#(free_ptr - 0x46C00)]! ; __imp_free
.plt:00011C00 ; End of function free
```

CFG fast doesn't recognize "free" function stub, instead I have:
```
Function name: sub_11bf5
+----------------+-------------+--------------+
| Block addres   | Inst. num   | Block size   |
+================+=============+==============+
| 0x11bf5        | 1           | 2            |
+----------------+-------------+--------------+
| 0x11bf8        | 3           | 12           |
+----------------+-------------+--------------+
```

**Comment by rhelmot** [comment] 2018-07-12 00:16
I mean... that's a a pretty good answer too. What's the benefit in calling those two separate functions instead of just one function that does an arm/thumb switch in the middle? Does anyone but j_free jump directly to 0x11bf8?

**Comment by ArtemShypotilov** [comment] 2018-07-12 07:48
Audrey, 

I also don't quite understand what is the reasoning behind this, but gcc creates such PLT entries from time to time besides usual ones.

0x11bf8 is referenced only by j_free jump. Other code uses j_free, when it needs to perform free call. 

However, there are cases, when both functions are referenced (for example, j_memcpy - 0x011c4c and memcpy - 0x011c50) . For them, angr produces following:

```
Function name: sub_11c4d
+----------------+-------------+--------------+
| Block addres   | Inst. num   | Block size   |
+================+=============+==============+
| 0x11c4d        | 1           | 2            |
+----------------+-------------+--------------+

Function name: memcpy
+----------------+-------------+--------------+
| Block addres   | Inst. num   | Block size   |
+================+=============+==============+
| 0x11c50        | 3           | 12           |
+----------------+-------------+--------------+
```

I've attached binary just in case - [wget.zip](https://github.com/angr/angr/files/2187586/wget.zip).

**Comment by rhelmot** [comment] 2018-07-12 07:57
The question is, why is it useful to consider those two stubs as different functions, other than "ida says so"? It seems to me that angr is producing a reasonably sane answer.

**Comment by ArtemShypotilov** [comment] 2018-07-12 08:07
Audrey,

As you can see, in case of memcpy, calls can be made either to 0x11c4d or to 0x11c50. So if I search memcpy callsites, I'll miss those made to address 0x11c4d. I believe thats the only problem.

**Comment by raycewest** [comment] 2019-09-16 19:47
necrobump?  I've seen this in the wild as well.

**Comment by ltfish** [comment] 2019-09-16 20:59
@rhelmot `bx pc` should jump to two instructions ahead of the current end of the block because in ARM pc always points to two instructions ahead of the current instruction being executed.

Thanks for bumping this issue up. I'll get it fixed.

**Comment by raycewest** [comment] 2019-09-17 15:17
for the meantime and anyone reading:  is there a way to add one of these thunk nodes in manually to an existing CFGFast?  I've looked for a bit and don't see a way; I need a way to gather call sites to these.  Specifying them as function_start's doesn't seem to work either.  Thanks!

**Comment by ltfish** [comment] 2020-02-22 05:29
@ArtemShypotilov  Sorry for the late reply. I looked into this issue again and I believe that angr (and IDA) is not doing anything wrong here. In your example, `sub_11c4d` is the PLT entry for THUMB mode code to call `memcpy`, and `memcpy` (at 0x11c50) is the PLT entry for ARM mode code to call `memcpy`. If you need to figure out all locations where `memcpy` is called, you should find callers to _both_ function 0x11c50 and function 0x11c4d.

**Closed** 2022-06-16 23:28 UTC
Labels: question
