### ISSUE TITLE
Single-instruction stepping on MIPS causes incorrect results

### ISSUE THREAD

**Issue by WGH-** [angr/angr#71] opened 2016-03-22 19:54 UTC
Using `path.step(num_inst=1)` on MIPS architecture causes incorrect results if branch is involved due to delay slots. 

So consider a `jal 0x00400770`, followed by `addu $at, $zero` (essentially NOP). In binary, it would be `b"\xDC\x01\x10\x0C\x21\x08\x20\x00"`.

Let's take them both and observe that the result is correct.
```
In [6]: pyvex.IRSB(b"\xDC\x01\x10\x0C\x21\x08\x20\x00", 0x4009FC, archinfo.ArchMIPS32()).pp()
IRSB {
   t0:Ity_I32 t1:Ity_I32 t2:Ity_I32 t3:Ity_I32

   00 | IR-NoOp
   01 | IR-NoOp
   02 | IR-NoOp
   03 | IR-NoOp
   04 | IR-NoOp
   05 | IR-NoOp
   06 | IR-NoOp
   07 | IR-NoOp
   08 | IR-NoOp
   09 | IR-NoOp
   10 | IR-NoOp
   11 | IR-NoOp
   12 | IR-NoOp
   13 | IR-NoOp
   14 | IR-NoOp
   15 | ------ IMark(0x4009fc, 4, 0) ------
   16 | PUT(ra) = 0x00400a04
   17 | t0 = 0x00400770
   18 | PUT(pc) = 0x00400a00
   19 | ------ IMark(0x400a00, 4, 0) ------
   20 | t2 = GET:I32(at)
   21 | t1 = Add32(t2,0x00000000)
   22 | PUT(at) = t1
   23 | PUT(pc) = t0
   24 | t3 = GET:I32(pc)
   NEXT: PUT(pc) = t3; Ijk_Call
}
```

Now, let's check them one by one:
```
In [5]: pyvex.IRSB(b"\xDC\x01\x10\x0C", 0x4009FC, archinfo.ArchMIPS32()).pp()
IRSB {
   t0:Ity_I32 t1:Ity_I32

   00 | IR-NoOp
   01 | IR-NoOp
   02 | IR-NoOp
   03 | IR-NoOp
   04 | IR-NoOp
   05 | IR-NoOp
   06 | IR-NoOp
   07 | IR-NoOp
   08 | IR-NoOp
   09 | IR-NoOp
   10 | IR-NoOp
   11 | IR-NoOp
   12 | IR-NoOp
   13 | IR-NoOp
   14 | IR-NoOp
   15 | ------ IMark(0x4009fc, 4, 0) ------
   16 | PUT(ra) = 0x00400a04
   17 | t0 = 0x00400770
   18 | PUT(pc) = 0x00400a00
   19 | t1 = GET:I32(pc)
   NEXT: PUT(pc) = t1; Ijk_Boring
}
In [8]: pyvex.IRSB(b"\x21\x08\x20\x00", 0x400A00, archinfo.ArchMIPS32()).pp()
IRSB {
   t0:Ity_I32 t1:Ity_I32 t2:Ity_I32

   00 | IR-NoOp
   01 | IR-NoOp
   02 | IR-NoOp
   03 | IR-NoOp
   04 | IR-NoOp
   05 | IR-NoOp
   06 | IR-NoOp
   07 | IR-NoOp
   08 | IR-NoOp
   09 | IR-NoOp
   10 | IR-NoOp
   11 | IR-NoOp
   12 | IR-NoOp
   13 | IR-NoOp
   14 | IR-NoOp
   15 | ------ IMark(0x400a00, 4, 0) ------
   16 | t1 = GET:I32(at)
   17 | t0 = Add32(t1,0x00000000)
   18 | PUT(at) = t0
   19 | PUT(pc) = 0x00400a04
   20 | t2 = GET:I32(pc)
   NEXT: PUT(pc) = t2; Ijk_Boring
}
```
Branch is lost.

**Comment by ltfish** [comment] 2016-03-22 19:59
That is because VEX requires the delay-slot to exist for any branch instruction on MIPS. You simply cannot list MIPS machine code instruction by instruction.

**Comment by WGH-** [comment] 2016-03-22 20:02
Of course, that's exactly what I found.

The problem is, `Path.step` **silently** produces incorrect results instead of raising exception.

**Comment by rhelmot** [comment] 2016-03-22 20:04
Oh, well why didn't you say so? Give me five minutes and I can make the lifter freak out if you're doing that. 

The bottom line is that stepping in increments of less than one basic block is for educational and debugging purposes only and it WILL mess things in VEX up.

**Comment by ltfish** [comment] 2016-03-22 20:06
I don't think by default `path.step` will stop before the delay-slot. How are you calling `path.step`? Are you specifying how many instructions you want to execute or the maximum bytes you wanna include in the next basic block?

**Comment by rhelmot** [comment] 2016-03-22 20:07
`path.step(num_inst=1)` is the first line of this issue :P

**Comment by ltfish** [comment] 2016-03-22 20:08
And as what @rhelmot said, stepping a path with less than one basic block is not guaranteed to always work, and this is one of the issues one can expect.

@rhelmot: We should put it in our documentation.

**Comment by zardus** [comment] 2016-03-22 20:10
Guys, that's silly. Of course we can step one instruction at a time. MIPS is an exception to that, but forcing the single-stepping ability into the realm of "educational and debugging purposes" is a mistake, IMO.

I think the lifter should complain loudly if you try to single-step over a jump, but we can do that without wrecking/discouraging useful functionality.

**Comment by ltfish** [comment] 2016-03-22 20:14
@zardus I'm not sure if that's easily doable in VEX though. It's probably easier to just do it in PyVEX or in `Path.step()`, but I cannot come with any solution that doesn't incur too much overhead (we'll have to lift all instructions twice on MIPS to see if there is a delay-slot afterwards).

**Comment by rhelmot** [comment] 2016-03-22 20:14
Something we should also consider is that this issue has applications for normal analysis as well - if there's a block, including delay slot instruction, that is exactly 100 instructions long, VEX will cut it off at 99 instructions, ending with the jump instruction but missing the jump slot, and cause this issue.

Really, VEX was designed with the intent in mind of being a sequential translator, and one of our patches was to make the delay slot static data NOT persist over translations because that was causing serious issues with some of our uses of VEX, e.g. for patching single instructions.

What we can do is to check if a vex block for MIPS ends with a jump instruction but not its delay slot, and manually cut off the jump instruction if it does. This'll force the issue for the single-instruction case, by returning an empty block and halting execution, and fix the 100-instruction-block case by making the jump show up in the next block entirely.

And of course we can complain loudly if we try to single-step mips code. Should the complaint be a logging message (warning or error?) or an exception?

**Comment by rhelmot** [comment] 2016-03-22 20:16
@ltfish we can either use capstone to lift the last instruction of the block by itself, use vex to lift the last two instructions of the block by themselves, just manually identify the IR that vex produces for a jump without a delay slot, or add a bogus NoOp IROp that signifies the jump instruction (patch VEX again) so we can recognize it.

**Comment by ltfish** [comment] 2016-03-22 20:19
@rhelmot I don't want any of our core functionality to rely on capstone. I still cannot install capstone in PyPy.

The most performant way is still patching VEX. I think we should just make VEX complain loudly when a delay-slot is missing (due to instruction limit or byte limit) for a branch instruction.

**Comment by rhelmot** [comment] 2016-03-22 20:26
VEX's only way of complaining is by throwing an exception and halting execution, which is unacceptable given that this can happen in real code without the num_insn parameter set, and also because this situation arises all the goddamn time in fidget. I think the following is acceptable:

- Patch pyvex to:
- look at the IRStmts of the last instruction of any MIPS block that ends in an Ijk_Boring jumping to the instruction immediately after the block
- If they *look* like they could be from a jump instruction without a delay slot (heuristics):
- Do a quick 3-instruction lift that includes the last two instructions that were previously lifted and the instruction immediately following the block
- If the result is 3 instructions long and jumps to somewhere other than immediately after it, lop the last instruction off of the original block before returning it.

**Comment by ltfish** [comment] 2016-03-22 20:34
PyVEX may not have all bytes that are needed. Note that those bytes are passed in from the user. When user is only passing in 100 bytes which "luckily" truncates between the branch instruction and the delay-slot, there is nothing PyVEX can do.

To me, raising an exception in VEX and catching that in `angr.Block.lift()` seems to be a better solution, where we can decide if we want to pass in more bytes, pass in less bytes (which will end the IRSB before the branch instruction), or raise another exception to the caller.

**Comment by zardus** [comment] 2016-03-22 20:37
My *STRONG* suggestion is to avoid any more modifications to VEX if possible. If we need to lift MIPS to VEX twice, let's do that, but we should be striving for less VEX modification, not more.

We should be able to get away with lifting MIPS blocks less than twice. We can lift the whole block, understand where it ends, and figure out if we can single-step (or need to double-step) the instructions in that block.

**Comment by rhelmot** [comment] 2016-03-22 20:39
@zardus my understanding of VEX's architecture is that this patch would be about four lines in one place, and would be extremely easy to maintain.

**Comment by zardus** [comment] 2016-03-22 20:47
Yes, but we're collection quite a bit of these 4-line patches that are extremely easy to maintain, and we have to maintain all of them and don't even have a good list of them anywhere.

IMO, the capstone method (see if the instruction we lifted is a jump, and lift two if we're in MIPS) is much better than patching VEX. We'll have to deal with the pypy thing, but that (getting capstone working with pypy) at least has a chance of getting upstreamed, wheras patching VEX is pure wasted effort that just leaves us with a higher maintenance load.

**Comment by ltfish** [comment] 2016-03-22 20:58
I don't want to make capstone a _necessary_ part of our dependence (right now angr still works without capstone installed). And the capstone approach is also slower. I'm seriously against it.

I feel patching VEX on this issue is a "more correct" and "cleaner" solution. Instead of having workarounds outside, inserting several lines to VEX code is not the end of the world. Saying this, none of us have tried to get our patches upstream for VEX, and maybe it's time to get the ball rolling. Personally I'd rather do this sort of stuff in the "correct" way, especially when the "correct" way has the least performance cost.

Alternatively, we can always pass four more bytes to PyVEX (but keep the `max_bytes` the same, i.e. `4` for a single instruction on MIPS). Then what @rhelmot proposed can work. The exception handling should be done in `angr.Block.lift` though, so user can decide what to do in such cases.

**Comment by zardus** [comment] 2016-03-22 21:04
Inserting several lines into VEX once is not the end of the world. Twice might be ok. Three times, sure. But we have literally hundreds of lines in VEX, and we have no sort of accounting of what they are or what they do. I see this is one of the major maintainability issues in angr, and continuing to blindly roll in this direction is wrong. That's what gets us into VINE and old-BAP territory.

We already use capstone in CFG generation on ARM to deal with thumb stuff, btw.

I'm totally fine with your alternative. That way, it can be nicely contained in pyvex, at least. It'll still require lifting twice, though, so keep that in mind.

**Comment by ltfish** [comment] 2016-03-22 21:09
> We already use capstone in CFG generation on ARM to deal with thumb stuff, btw.

I'm inclined to remove that in the future. Just don't have time to do it now.

> But we have literally hundreds of lines in VEX, and we have no sort of accounting of what they are or what they do.

The situation is not that bad. We have git commit history for everything. Essentially we are maintaining a bunch of custom patches, which is a practice that many open-source projects do. IMHO we should try to get things upstreamed to VEX. I can take the lead on this matter as soon as I get back to west coast.

**Comment by ltfish** [comment] 2016-03-25 01:06
@rhelmot @zardus what's our final decision?

**Comment by zardus** [comment] 2016-03-25 21:39
Now that we've had the debate, let's just go with the standard open source approach: whoever actually implements it will end up deciding.

**Comment by ltfish** [comment] 2016-03-25 21:42
Great, I like it!

**Comment by dovf** [comment] 2016-07-05 19:30
So does that mean I get to decide...? ;)

I've submitted a PR in vex, which is along the lines of the fix proposed by @ltfish: vex now returns a decode failure if an attempt is made to decode a branch or jump as a single instruction.

Regarding @rhelmot's concern about this occuring in other situations besides single-stepping (e.g., by a block that gets cut off exactly between the branch or jump and its delay slot): it turns out that vex already handles this case, just not if the last instruciton is also the first instruction (see commit message at https://github.com/dovf/vex/commit/2df16473f579a7963ff06c9175ceedea31cdeeb2).

The effect of this fix on angr is that now an attempt to lift a single instruction which is a branch or jump will return an empty block, with jumpkind 'Ijk_NoDecode'. Then, an attempt to step the block results in an exception (`SimIRSBError('Empty IRSB passed to SimIRSB.')`) which either causes the path to become errored, or immediately raises in exception (if `throw=True`). This situation can be detected, and then the lifting can be attempted again, this time with `num_inst=2`.

The problem with this is that it's not very clear from the exception raised what the problem actually was; I was initially tempted to detect the 'Ijk_NoDecode' in pyvex and to raise a more explicit exception (see https://github.com/dovf/pyvex/commit/2d30f73a828ea10121d86ddf65e4e5b6bd6cccfc). However, this caused some tests to fail (some pickling tests -- because the returned c_irsb is not pickleable, and the exception was being raised before that is fixed; this could be worked around by moving the exception detection until after the pickling is fixed, but... -- and some other tests which explicitly check for the no-decode case (because of corrupt instructions); these issues could probably be fixed by making the detection more and more specific to the specific case we're looking for, but that seems like too much of a kludge... So for the moment I think that just the fix in vex is good enough, or at least better than the current situation...

(This is my first foray into angr, so feel free to correct whatever's necessary -- and thanks for the wonderful tool!)

**Comment by ltfish** [comment] 2016-07-05 19:52
First of all, thanks for picking this issue up!

Your patch in VEX makes sense to me.  Regarding the commit in PyVEX, raising an exception for `NoDecode` is not what angr expects. For now, I think it suffices to just document in `pyvex.IRSB` about the 'NoDecode' behavior on MIPS.

**Comment by ltfish** [comment] 2016-07-05 19:53
> and thanks for the wonderful tool

Thank you for using angr and making contributions :-)

**Comment by dovf** [comment] 2016-07-05 21:21
> For now, I think it suffices to just document in pyvex.IRSB about the 'NoDecode' behavior on MIPS.

Done -- PR angr/pyvex#35 -- hope it's not too verbose...

**Comment by ltfish** [comment] 2016-07-05 21:48
Your PRs look great. I'll merge them in once we resolved the desyncing issue on our side. Thanks!

**Comment by dovf** [comment] 2016-08-15 20:57
Hey, guys! Just wanted to make sure this is still on your radar as you prepare the upcoming release of angr? Thanks!

**Comment by ltfish** [comment] 2016-08-15 21:34
Yep, at least it's on my radar!

I'll be very busy in the next 36 hours. Hopefully someone else can take care of it. Otherwise I'll merge it in after the chaos on my side!

**Closed** 2016-08-16 05:41 UTC

**Comment by rhelmot** [comment] 2016-08-16 05:44
I should technically be involved in the chaos but I'm sitting this one out :)

**Comment by dovf** [comment] 2016-08-16 15:55
Thanks for pulling!
Which chaos is it this time? I waited until after the CGC finals, plus a bit of breathing space ;)
