### ISSUE TITLE
Hit a symbolic conditional operation. Something has gone wildly wrong.

### ISSUE THREAD

**Issue by gkso** [angr/angr#2472] opened 2021-01-12 23:03 UTC
---

**Describe the bug.**

I was running angr on some 32-bit ARM binary. And it throws a SimError("Hit a symbolic conditional operation. Something has gone wildly wrong.") when handling the instruction "movne r0, r0, rrx". 

The stack trace:

```
  /home/alan/Work/angr-dev/angr/angr/sim_manager.py(346)step()
-> successors = self.step_state(state, successor_func=successor_func, **run_args)
  /home/alan/Work/angr-dev/angr/angr/sim_manager.py(383)step_state()
-> successors = self.successors(state, successor_func=successor_func, **run_args)
  /home/alan/Work/angr-dev/angr/angr/sim_manager.py(422)successors()
-> return self._project.factory.successors(state, **run_args)
  /home/alan/Work/angr-dev/angr/angr/factory.py(60)successors()
-> return self.default_engine.process(*args, **kwargs)
  /home/alan/Work/angr-dev/angr/angr/engines/vex/light/slicing.py(19)process()
-> return super().process(*args, **kwargs)
  /home/alan/Work/angr-dev/angr/angr/engines/engine.py(149)process()
-> self.process_successors(self.successors, **kwargs)
  /home/alan/Work/angr-dev/angr/angr/engines/failure.py(21)process_successors()
-> return super().process_successors(successors, **kwargs)
  /home/alan/Work/angr-dev/angr/angr/engines/syscall.py(18)process_successors()
-> return super().process_successors(successors, **kwargs)
  /home/alan/Work/angr-dev/angr/angr/engines/hook.py(54)process_successors()
-> return super().process_successors(successors, procedure=procedure, **kwargs)
  /home/alan/Work/angr-dev/angr/angr/engines/unicorn.py(169)process_successors()
-> return super().process_successors(successors, **kwargs)
  /home/alan/Work/angr-dev/angr/angr/engines/soot/engine.py(64)process_successors()
-> return super().process_successors(successors, **kwargs)
  /home/alan/Work/angr-dev/angr/angr/engines/vex/heavy/heavy.py(136)process_successors()
-> self.handle_vex_block(irsb)
  /home/alan/Work/angr-dev/angr/angr/engines/vex/heavy/super_fastpath.py(19)handle_vex_block()
-> super().handle_vex_block(irsb)
  /home/alan/Work/angr-dev/angr/angr/engines/vex/light/slicing.py(26)handle_vex_block()
-> super().handle_vex_block(irsb)
  /home/alan/Work/angr-dev/angr/angr/engines/vex/heavy/actions.py(30)handle_vex_block()
-> super().handle_vex_block(irsb)
  /home/alan/Work/angr-dev/angr/angr/engines/vex/heavy/inspect.py(45)handle_vex_block()
-> super().handle_vex_block(irsb)
  /home/alan/Work/angr-dev/angr/angr/engines/vex/light/light.py(446)handle_vex_block()
-> self._handle_vex_stmt(stmt)
  /home/alan/Work/angr-dev/angr/angr/engines/vex/light/slicing.py(30)_handle_vex_stmt()
-> super()._handle_vex_stmt(stmt)
  /home/alan/Work/angr-dev/angr/angr/engines/vex/heavy/inspect.py(40)_handle_vex_stmt()
-> super()._handle_vex_stmt(stmt)
  /home/alan/Work/angr-dev/angr/angr/engines/vex/light/resilience.py(36)inner()
-> return getattr(super(VEXResilienceMixin, self), func)(*iargs, **ikwargs)
  /home/alan/Work/angr-dev/angr/angr/engines/vex/heavy/heavy.py(202)_handle_vex_stmt()
-> super()._handle_vex_stmt(stmt)
  /home/alan/Work/angr-dev/angr/angr/engines/vex/light/light.py(51)_handle_vex_stmt()
-> handler(stmt)
  /home/alan/Work/angr-dev/angr/angr/engines/vex/light/light.py(188)_handle_vex_stmt_WrTmp()
-> self._analyze_vex_stmt_WrTmp_data(stmt.data)
  /home/alan/Work/angr-dev/angr/angr/engines/vex/light/light.py(184)_analyze_vex_stmt_WrTmp_data()
-> def _analyze_vex_stmt_WrTmp_data(self, *a, **kw): return self. _handle_vex_expr(*a, **kw)
  /home/alan/Work/angr-dev/angr/angr/engines/vex/heavy/inspect.py(31)_handle_vex_expr()
-> return super()._handle_vex_expr(expr)
  /home/alan/Work/angr-dev/angr/angr/engines/vex/light/light.py(55)_handle_vex_expr()
-> result = handler(expr)
  /home/alan/Work/angr-dev/angr/angr/engines/vex/light/light.py(98)_handle_vex_expr_CCall()
-> [self._analyze_vex_expr_CCall_arg(arg) for arg in expr.args],
  /home/alan/Work/angr-dev/angr/angr/engines/vex/heavy/actions.py(70)_perform_vex_expr_CCall()
-> result = super()._perform_vex_expr_CCall(func_name, ty, exprs, func=None)
  /home/alan/Work/angr-dev/angr/angr/engines/vex/light/resilience.py(36)inner()
-> return getattr(super(VEXResilienceMixin, self), func)(*iargs, **ikwargs)
  /home/alan/Work/angr-dev/angr/angr/engines/vex/heavy/heavy.py(297)_perform_vex_expr_CCall()
-> return super()._perform_vex_expr_CCall(func_name, ty, args, func=None)
  /home/alan/Work/angr-dev/angr/angr/engines/vex/claripy/datalayer.py(116)_perform_vex_expr_CCall()
-> return func(self.state, *args)
  /home/alan/Work/angr-dev/angr/angr/engines/vex/claripy/ccall.py(1559)armg_calculate_condition()
-> concrete_cond_n_op = op_concretize(cond_n_op)
> /home/alan/Work/angr-dev/angr/angr/engines/vex/claripy/ccall.py(51)op_concretize()
-> raise SimError("Hit a symbolic conditional operation. Something has gone wildly wrong.")
```

The IR block:

```
   00 | ------ IMark(0x7a740, 4, 0) ------
   01 | t1 = GET:I32(r3)
   02 | t0 = Shl32(t1,0x08)
   03 | ------ IMark(0x7a744, 4, 0) ------
   04 | t6 = GET:I32(r2)
   05 | t4 = Shl32(t6,0x08)
   06 | t7 = Sub32(t0,t4)
   07 | ------ IMark(0x7a748, 4, 0) ------
   08 | t92 = CmpEQ32(t0,t4)
   09 | t10 = GET:I32(r12)
   10 | t13 = And32(t10,0x00ff0000)
   11 | t95 = Xor32(t0,t7)
   12 | t97 = Xor32(t0,t4)
   13 | t94 = And32(t97,t95)
   14 | t93 = Shr32(t94,0x1f)
   15 | t98 = ITE(t92,0x00000005,0x00000002)
   16 | t99 = ITE(t92,t13,t0)
   17 | t100 = ITE(t92,0x00000000,t4)
   18 | t101 = ITE(t92,t93,0x00000000)
   19 | ------ IMark(0x7a74c, 4, 0) ------
   20 | t102 = armg_calculate_condition(t98,t99,t100,t101):Ity_I32
   21 | t21 = Sub32(t1,t6)
   22 | t64 = CmpNE32(t102,0x00000000)
   23 | t103 = ITE(t64,t21,t7)
   24 | t104 = ITE(t64,0x00000002,t98)
   25 | PUT(cc_op) = t104
   26 | t105 = ITE(t64,t1,t99)
   27 | PUT(cc_dep1) = t105
   28 | t106 = ITE(t64,t6,t100)
   29 | PUT(cc_dep2) = t106
   30 | t107 = ITE(t64,0x00000000,t101)
   31 | PUT(cc_ndep) = t107
   32 | ------ IMark(0x7a750, 4, 0) ------
   33 | t73 = Or32(t104,0x00000010)
   34 | t108 = armg_calculate_condition(t73,t105,t106,t107):Ity_I32
   35 | t109 = armg_calculate_flag_c(t104,t105,t106,t107):Ity_I32
   36 | t85 = Shr32(t103,0x01)
   37 | t86 = Shl32(t109,0x1f)
   38 | t84 = Or32(t86,t85)
   39 | t89 = CmpNE32(t108,0x00000000)
   40 | t110 = ITE(t89,t84,t103)
   41 | PUT(r0) = t110
   42 | ------ IMark(0x7a754, 4, 0) ------
   43 | t29 = GET:I32(lr)
   NEXT: PUT(pc) = t29; Ijk_Ret
```

The instruction causing the error:

`t108 = armg_calculate_condition(t73,t105,t106,t107):Ity_I32`

The values of t73, t105, t106, t107:

t73: 
<BV32 (if (if (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8 == 0x6d655200 then (0#31 .. (if (if (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8 == 0x6d655200 then 0x0 else (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8) == 0x0 then 1 else 0)) else (0#31 .. (if (if (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8 == 0x6d655200 then 0x0 else (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8) - (if (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8 == 0x6d655200 then 0x0 else 0x6d655200) == 0x0 then 1 else 0))) != 0x0 then 0x2 else (if (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8 == 0x6d655200 then 0x5 else 0x2)) | 0x10>

t105:
<BV32 if (if (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8 == 0x6d655200 then (0#31 .. (if (if (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8 == 0x6d655200 then 0x0 else (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8) == 0x0 then 1 else 0)) else (0#31 .. (if (if (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8 == 0x6d655200 then 0x0 else (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8) - (if (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8 == 0x6d655200 then 0x0 else 0x6d655200) == 0x0 then 1 else 0))) != 0x0 then (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) else (if (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8 == 0x6d655200 then 0x0 else (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8)>

t106:
<BV32 if (if (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8 == 0x6d655200 then (0#31 .. (if (if (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8 == 0x6d655200 then 0x0 else (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8) == 0x0 then 1 else 0)) else (0#31 .. (if (if (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8 == 0x6d655200 then 0x0 else (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8) - (if (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8 == 0x6d655200 then 0x0 else 0x6d655200) == 0x0 then 1 else 0))) != 0x0 then 0x6f6d6552 else (if (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8 == 0x6d655200 then 0x0 else 0x6d655200)>

t107:
<BV32 if (if (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8 == 0x6d655200 then (0#31 .. (if (if (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8 == 0x6d655200 then 0x0 else (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8) == 0x0 then 1 else 0)) else (0#31 .. (if (if (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8 == 0x6d655200 then 0x0 else (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8) - (if (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8 == 0x6d655200 then 0x0 else 0x6d655200) == 0x0 then 1 else 0))) != 0x0 then 0x0 else (if (input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8 == 0x6d655200 then LShR(((input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8 ^ 0x6d655200) & ((input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8 ^ ((input_buffer_0 .. input_buffer_1 .. input_buffer_2 .. input_buffer_3) << 0x8) - 0x6d655200), 0x1f) else 0x0)>

**Environment Information.**

angr environment report
=============================
Date: 2021-01-12 15:01:43.074966
Running in virtual environment at /home/alan/.virtualenvs/angr
Platform: linux-x86_64
Python version: 3.7.9 (7e6e2bb30ac5, Nov 18 2020, 10:55:52)
[PyPy 7.3.3-beta0 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
######## angr #########
Python found it in /home/alan/Work/TaSymEx/angr-dev/angr/angr
Pip version angr 9.0.gitrolling
Git info:
	Current commit f30bca25ea11db26c0430e91480e9b018ed45d85 from branch master
	Checked out from remote origin: https://github.com/angr/angr
######## ailment #########
Python found it in /home/alan/Work/TaSymEx/angr-dev/ailment/ailment
Pip version ailment 9.0.gitrolling
Git info:
	Current commit 8751ab2aa9c4b9301be52c07029fd6ef59c9d6d5 from branch master
	Checked out from remote origin: https://github.com/angr/ailment
######## cle #########
Python found it in /home/alan/Work/TaSymEx/angr-dev/cle/cle
Pip version cle 9.0.gitrolling
Git info:
	Current commit 7f3263c74a2c038234f5ec6adf8ebb4bf119e868 from branch master
	Checked out from remote origin: https://github.com/angr/cle
######## pyvex #########
Python found it in /home/alan/Work/TaSymEx/angr-dev/pyvex/pyvex
Pip version pyvex 9.0.gitrolling
Git info:
	Current commit 38af62047b8a7785feeee6b5f243ad1dbd7db1f6 from branch master
	Checked out from remote origin: https://github.com/angr/pyvex
######## claripy #########
Python found it in /home/alan/Work/TaSymEx/angr-dev/claripy/claripy
Pip version claripy 9.0.gitrolling
Git info:
	Current commit 5523a11e622ce7add618276be180c46c4d20785e from branch master
	Checked out from remote origin: https://github.com/angr/claripy
######## archinfo #########
Python found it in /home/alan/Work/TaSymEx/angr-dev/archinfo/archinfo
Pip version archinfo 9.0.gitrolling
Git info:
	Current commit f5712a1fe0fbc315c4e9bbcf96582e139f745b33 from branch master
	Checked out from remote origin: https://github.com/angr/archinfo
######## z3 #########
Python found it in /home/alan/.virtualenvs/angr/site-packages/z3
Pip version z3-solver 4.8.9.0
Couldn't find git info
######## unicorn #########
Python found it in /home/alan/.virtualenvs/angr/site-packages/unicorn
Pip version unicorn 1.0.2rc4
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/alan/Work/TaSymEx/angr-dev/angr/angr/lib/angr_native.so', handle 23d2d40 at 0x7f6a35750bb8>
unicorn: <CDLL '/home/alan/.virtualenvs/angr/site-packages/unicorn/lib/libunicorn.so', handle 17d3730 at 0x7f6a3eb31398>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x00007f6a3f1acb80>
z3: <CDLL '/home/alan/.virtualenvs/angr/site-packages/z3/lib/libz3.so', handle 1ac5470 at 0x7f6a3b606db0>

**To Reproduce.**

**Additional context.**

**Comment by MrMatch246** [comment] 2022-08-17 16:53
Any news on this end? it would be awesome if you would include the op in the exception so that people can actually debug without like having to use a custom angr version just to see whats the problem

**Comment by rhelmot** [comment] 2022-08-22 17:49
I _believe_ I've fixed this since january 2021, but I don't know for sure since there's no testcase to reproduce :)

I've added the diagnostic you requested in the above commit, but I don't particularly see how it helps debug the issue?

**Comment by ltfish** [comment] 2022-11-23 22:26
We are going to close this issue since a potential fix has been merged. Please re-open this issue if it's still broken for you. Thanks.

**Closed by ltfish** 2022-11-23 22:26 UTC
Labels: bug
