### ISSUE TITLE
Import Struggles on Python3.6

### ISSUE THREAD

**Issue by greek-stasia** [angr/angr#1790] opened 2019-11-07 23:42 UTC
I've been trying to run angr in Python 3. Every time I do:
`>>> import angr
`
I get the following:

![angr](https://user-images.githubusercontent.com/24921719/68437182-3ab2c680-018e-11ea-8368-1fe32073bdce.png)

I'm using Ubuntu 18 and Python 3.6

To reproduce:
`$python3`
`>>> import angr`

I'm not sure where this is coming from. I've used angr in Python2 on my Ubuntu 16 VM and I installed both in a similar fashion.
If someone could give me some guidance on how to debug this massive traceback I'd greatly appreciate it!

**Comment by rhelmot** [comment] 2019-11-07 23:45
seemingly a duplicate of https://github.com/angr/angr-dev/issues/89, which we were never able to solve either. it seems like a strange version mismatch with the protobuf library itself, but we were never to figure out why.

**Comment by pharaohW** [comment] 2019-11-12 08:49
I got the same error。So how can I bypass it?  try to use python 3.5?

**Comment by pharaohW** [comment] 2019-11-12 09:02
I fix it by
`pip install -U protobuf`

**Comment by ltfish** [comment] 2019-11-13 00:56
It seems that we should pin to newer protobuf versions in our `setup.py`.

**Comment by rhelmot** [comment] 2019-11-15 00:32
@greek-stasia does `pip install -U protobuf` fix it for you as well?

**Closed** 2022-06-16 23:31 UTC
Labels: question
