### ISSUE TITLE
ARM issue: `lr` modification in a basic block causes branches to be classified as calls

### ISSUE THREAD

**Issue by zardus** [angr/angr#342] opened 2017-01-27 00:01 UTC
VEX seems to have a heuristic where it will classify the branches in a basic block that has modifications to the link register as calls. This causes false positives when `lr` is used as a general purpose register and wreaks havoc on analyses.

We should investigate how to work around this.

**Comment by zardus** [comment] 2017-01-27 00:01
@ltfish and @badnack, as interested parties

**Comment by rhelmot** [comment] 2017-01-27 01:19
This is a duplicate of https://github.com/angr/angr/issues/307 :)

The culprit is not vex, but our postprocessor.

**Closed by rhelmot** 2017-01-27 01:19 UTC

**Comment by zardus** [comment] 2017-01-27 01:21
Hahaha!

TFW your binary analysis engine gets too big for your own brain :-)
