### ISSUE TITLE
Different return value endness for SimProcedure vs native fn

### ISSUE THREAD

**Issue by smclaugh** [angr/angr#1687] opened 2019-07-26 17:49 UTC
**Explanation**

When inspecting `'reg_write'`, return values have different endness when coming from SimProcedures vs native functions.

In the SimProcedure case, the bytes are `reversed` in [`_standardize_value`](https://github.com/angr/angr/blob/master/angr/calling_conventions.py#L832). This happens _before_ [inspecting `reg_write`](https://github.com/angr/angr/blob/master/angr/storage/memory.py#L524).

However, in the native function case, the bytes are `reversed` in [symbolic_memory.py](https://github.com/angr/angr/blob/master/angr/state_plugins/symbolic_memory.py#L842). This happens _after_ [inspecting `reg_write`](https://github.com/angr/angr/blob/master/angr/storage/memory.py#L524).

**Reproduction**

```python
#!/usr/bin/env pypy3

import angr
import os

code = '''
// f() comes from hook_symbol() below.

int g() {
    return 0xb;
}

void main() {
    f();
    g();
}
'''
os.system('echo "%s" > x.c && gcc -c x.c' % code)

class SimpleSimProc(angr.SimProcedure):
    def run(self):
        return 0xb

def handle_reg_write(state):
    reg_offset = state.inspect.reg_write_offset
    reg_expr = state.inspect.reg_write_expr
    if state.arch.registers['rax'][0] == reg_offset:
        # Ignore values that aren't 0xb or 0xb00000...
        if reg_expr.args[0] != 0:
            print('I hope 0x%x == 0xb' % reg_expr.args[0])

p = angr.Project('./x.o')
s = p.factory.entry_state()

main_addr = [x for x in p.loader.symbols if x.name == 'main'][0].rebased_addr
s.regs.ip = s.solver.BVV(main_addr, s.arch.bits)

p.hook_symbol('f', SimpleSimProc(), replace=True)
s.inspect.b('reg_write', when=angr.BP_BEFORE, action=handle_reg_write)

p.factory.simgr(s).run()
```

Outputs:
```
...
I hope 0xb00000000000000 == 0xb
I hope 0xb == 0xb
```

**Environment**
```
$ pypy3 --version
Python 3.5.3 (928a4f70d3de, Feb 08 2019, 10:42:58)
[PyPy 7.0.0 with GCC 6.2.0 20160901]
$ python -c "import angr; print(angr.__version__)"
(8, 19, 4, 5)
$ uname -a
Linux ... 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
```

**Comment by rhelmot** [comment] 2019-07-29 20:26
The problem here is that one of the writes happens with `state.registers.write(value, endness='Iend_LE')` and the other write happens with `state.registers.write(value.reversed, endness='Iend_BE')`. This is in some way intended behavior. The problem is that the passed endness value is not exposed to the breakpoint.

Implementing this is kind of complicated... It would be easy if you were willing to accept `None` as a valid endness value and manually did the swaps for each arch correctly, but if you needed the value to always be populated with BE or LE, we would need to break some of the abstractions in order to figure out what the default value is in time to fire the breakpoint.

**Comment by rhelmot** [comment] 2019-07-29 20:37
just kidding; I'm full of shit. the linked commit should give you the tools you need to solve this. I'll merge it when it passes CI.

**Comment by rhelmot** [comment] 2019-07-29 21:04
Merged. You can now add `if state.inspect.reg_write_endness == 'Iend_BE: ...` in your breakpoint to handle this case.

**Closed** 2019-07-29 21:04 UTC
Labels: feature

**Comment by smclaugh** [comment] 2019-07-29 21:48
First of all, thank you very much!!

Second, can I just double check my understanding here: 

reg_write_endness == 'Iend_BE' ==> 'Iend_BE' was passed into store(), meaning that the value is actually little endian?

**Comment by rhelmot** [comment] 2019-07-29 22:18
Moderately complicated. It means that either Iend_BE was passed into store() OR that _no_ endness was passed into store() and the memory region's default endness is big-endian. Since, you know, the register file is modeled as a memory region by default.

If you were doing this on memory instead of registers, all memory in angr has a default endness of big-endian regardless of architecture. This is so that you can store large swaths of data a la memcpy and not have to try to apply endness to this store where the concept doesn't exist.

This is big lead-up to basically say that "the value is actually little-endian" is a phrasing which doesn't really need anything - it's just a value, it doesn't have an endness. However, if you're working with a register file where words are stored little-endian and you see a big-endian store, the value will need to have its bytes reversed in order to make sense. We can't really do that automatically for you because of a giant pile of optimizations in angr's memory model in order to minimize the amount of byteswapping that happens between store and load.

**Comment by smclaugh** [comment] 2019-07-29 23:13
Whew, tricky stuff! Thanks for clarifying.
