### ISSUE TITLE
I can't use veritesting

### ISSUE THREAD

**Issue by cha5126568** [angr/angr#299] opened 2016-12-25 10:27 UTC
I want to use veritesting with my project.
so, I found that examples of veritesting on angr-doc/examples/defcamp_r200/
However, when I run this example, I got an error that "angr.analyses.loops | No knowledge of function os present. Did you forget to construct a CFG"
![12341234](https://cloud.githubusercontent.com/assets/13634407/21470685/d9d29138-cad6-11e6-8621-57072afb4ece.PNG)

Although process is "very" slow, I was able to get results.
However, this speed is not suitable for my project.
I think that angr have problem
How can i fix this problem?
//Sorry for my english. English is not my native language.

**Comment by rhelmot** [comment] 2016-12-25 11:59
This is a duplicate of https://github.com/angr/angr/issues/293

The error message does not indicate that something is wrong.

Judging the speed of angr based on this particular example is probably not a very good idea. angr is not a program you run, angr is a toolkit you use. The example you are looking at is a very slow script.

There are lots of ways to make angr fast based on your use-case. We have written several of them here: https://docs.angr.io/docs/speed.html

**Closed** 2017-01-22 11:30 UTC
