### ISSUE TITLE
CFGFast dies on /bin/ls

### ISSUE THREAD

**Issue by Alexeyan** [angr/angr#1096] opened 2018-06-30 16:29 UTC
Hi. 

So angr's CFGFast is dying on /bin/ls, if the `auto_load_libs=False`-Option is **not** given.
The trace looks like it dies somewhere in the lifting code. 

Do you want the exact binary & libs to debug this?

```
p = angr.Project("/bin/ls")
cfg = p.analyses.CFGFast()

WARNING | 2018-06-30 18:24:17,877 | angr.analyses.disassembly_utils | Your version of capstone does not support MIPS instruction groups.                                                                                                    
WARNING | 2018-06-30 18:24:18,551 | cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.                                                                                  
WARNING | 2018-06-30 18:24:20,755 | angr.analyses.cfg.cfg_fast | "auto_load_libs" is enabled. With libraries loaded in project, CFGFast will cover libraries, which may take significantly more time than expected. You may reload the binary with "auto_load_libs" disabled, or specify "regions" to limit the scope of CFG recovery.
WARNING | 2018-06-30 18:24:27,413 | angr.engines.successors | Exit state has over 256 possible solutions. Likely unconstrained; skipping. <BV64 global_c000026_86_64{UNINITIALIZED}>                                                        
Traceback (most recent call last):
  File "<module>", line 1, in <module>
  File "/home/X/Projects/angr-dev/angr/angr/analyses/analysis.py", line 108, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/X/Projects/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 909, in __init__
    self._analyze()
  File "/home/X/Projects/angr-dev/angr/angr/analyses/forward_analysis.py", line 552, in _analyze
    self._analysis_core_baremetal()
  File "/home/X/Projects/angr-dev/angr/angr/analyses/forward_analysis.py", line 677, in _analysis_core_baremetal
    self._process_job_and_get_successors(job_info)
  File "/home/X/Projects/angr-dev/angr/angr/analyses/forward_analysis.py", line 695, in _process_job_and_get_successors                                                                                                                    
    successors = self._get_successors(job)
  File "/home/X/Projects/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1301, in _get_successors
    jobs = self._scan_block(addr, current_function_addr, jumpkind, src_node, src_ins_addr, src_stmt_idx)
  File "/home/X/Projects/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1576, in _scan_block
    previous_src_ins_addr, previous_src_stmt_idx)
  File "/home/X/Projects/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1748, in _scan_irsb
    stmt_idx
  File "/home/X/Projects/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1920, in _create_jobs
    target_addr, jumpkind, is_syscall=is_syscall
  File "/home/X/Projects/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 2014, in _create_job_call
    syscall=is_syscall, stmt_idx=stmt_idx, ins_addr=ins_addr)
  File "/home/X/Projects/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 3153, in _function_add_call_edge
    ret_snippet = self._to_snippet(addr=ret_addr, base_state=self._base_state)
  File "/home/X/Projects/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 501, in _to_snippet
    backup_state=base_state)
  File "/home/X/Projects/angr-dev/angr/angr/factory.py", line 46, in snippet
    return self.block(addr, **block_opts).codenode # pylint: disable=no-member
  File "/home/X/Projects/angr-dev/angr/angr/factory.py", line 288, in block
    strict_block_end=strict_block_end
  File "/home/X/Projects/angr-dev/angr/angr/block.py", line 61, in __init__
    strict_block_end=strict_block_end)
  File "/home/X/Projects/angr-dev/angr/angr/engines/vex/engine.py", line 519, in lift
    strict_block_end=strict_block_end)
  File "/home/X/Projects/angr-dev/pyvex/pyvex/block.py", line 82, in __init__
    lift(self, arch, mem_addr, data, max_bytes, max_inst, bytes_offset, opt_level, traceflags, strict_block_end)
  File "/home/X/Projects/angr-dev/pyvex/pyvex/lifting/__init__.py", line 109, in lift
    lift(more_irsb, arch, addr, data_left, max_bytes, max_inst, bytes_offset, opt_level, traceflags, inner=True)
  File "/home/X/Projects/angr-dev/pyvex/pyvex/lifting/__init__.py", line 110, in lift
    final_irsb.extend(more_irsb)
  File "/home/X/Projects/angr-dev/pyvex/pyvex/block.py", line 149, in extend
    stmt.expressions[i] = convert_expr(expr)
  File "/home/X/Projects/angr-dev/pyvex/pyvex/block.py", line 129, in convert_expr
    return RdTmp(convert_tmp(expr.tmp))
  File "/home/X/Projects/angr-dev/pyvex/pyvex/block.py", line 117, in convert_tmp
    tmp_type = extendwith.tyenv.lookup(tmp)
  File "/home/X/Projects/angr-dev/pyvex/pyvex/block.py", line 474, in lookup
    return self.types[tmp]
IndexError: list index out of range

```

**Comment by ltfish** [comment] 2018-06-30 16:47
Will be addressed later today.

**Comment by rhelmot** [comment] 2018-06-30 17:40
Is this on the most recent angr, with angr/pyvex#135? If so I have a guess what’s going on - the block extension code makes the assumption that all IR objects are unique, and mutates them in an algorithm that will break like that if references are shared. This could be fixed by tracking which references have been updated during block extension and not touching them twice.

**Comment by rhelmot** [comment] 2018-06-30 17:44
(That would make this the same issue as angr/pyvex#137, but I fixed that by making the rest of the code get out of the way of the block extension code. That’s my really an option here)

**Comment by ltfish** [comment] 2018-07-01 03:05
@Alexeyan It'll be great if you can upload your `ls` and your `libc.so`. I could not reproduce this problem on my machine.

@rhelmot That is a legitimate guess, but I did not find any place where `RdTmp.tmp` is modified now. In fact, `RdTmp.tmp` is not modifiable now - you have to go through `RdTmp._tmp` instead.

My guess is there is some bug with how `tyenv` is handled or processed in the extender.

**Comment by Alexeyan** [comment] 2018-07-01 04:22
@ltfish Here are them. Should be the default Arch bins.



[bug.zip](https://github.com/angr/angr/files/2152387/bug.zip)

**Comment by ltfish** [comment] 2018-07-01 04:58
Wow... OK I found the bug. Give me some time to come up with a solution... It's not easy to fix.

**Comment by ltfish** [comment] 2018-07-01 05:29
It seems that I found a solution. Eventually I can go take a shower without worrying about this bug.

@Alexeyan Thank you so much for reporting!

**Closed** 2018-07-01 18:12 UTC
Labels: bug
