### ISSUE TITLE
PyVex fails decoding thumb instructions

### ISSUE THREAD

**Issue by Paul1nh0** [angr/angr#1992] opened 2020-03-12 02:11 UTC
---

Hi all,

I have a simple thumb basic block like this

```
.text:00001DCA 47 F8 AC 0C     STR.W           R0, [R7,#-0xAC]
.text:00001DCE 68 46           MOV             R0, SP
.text:00001DD0 A0 F1 08 0D     SUB.W           SP, R0, #8
.text:00001DD4 69 46           MOV             R1, SP
```

I tried to create a Block and dump IR stmt in this way project.factory.block(0x401DCB).vex.pp(), the result is 

```
  00 | ------ IMark(0x401dca, 4, 1) ------
   01 | t2 = GET:I32(r7)
   02 | t3 = Sub32(t2,0x000000ac)
   03 | t4 = GET:I32(r0)
   04 | STle(t3) = t4
   05 | ------ IMark(0x401dce, 2, 1) ------
   06 | t7 = GET:I32(sp)
   07 | PUT(r0) = t7
   08 | ------ IMark(0x401dd0, 0, 1) ------
   09 | PUT(itstate) = 0x00000000
   NEXT: PUT(pc) = 0x00401dd1; Ijk_NoDecode
```

I want to know why PyVex fails decoding instructions at 0x401DD1?

Thank you!

**Comment by twizmwazin** [comment] 2020-03-12 03:34
Duplicate of angr/pyvex#205

**Closed by twizmwazin** 2020-03-12 03:34 UTC
