### ISSUE TITLE
Code block byte alignment is recognized as a function

### ISSUE THREAD

**Issue by p611148aadsl** [angr/angr#1710] opened 2019-09-04 07:51 UTC
Code block byte alignment is recognized as a function. This confused me. Is this the correct analysis?
![image](https://user-images.githubusercontent.com/11703999/64235613-4fbf6f00-cf2b-11e9-9d43-274cb2e9c198.png)

The following is the analysis result.
```
`(Pdb) self.project.kb.functions.function(0x400bcc)
<Function sub_400bcc (4197324)>

(Pdb) self.project.kb.functions.function(0x400bcc)._addr_to_block_node
{4197328: <BlockNode at 0x400bd0 (size 56)>, 4197324: <BlockNode at 0x400bcc (size 4)>}

(Pdb) self.project.kb.functions.function(0x400bd0)
<Function _ZN42CWE416_Use_After_Free__malloc_free_char_43L9badSourceERPc (4197328)>

(Pdb) self.project.kb.functions.function(0x400bd0)._addr_to_block_node
{4197328: <BlockNode at 0x400bd0 (size 56)>, 4197384: <BlockNode at 0x400c08 (size 52)>, 4197436: <BlockNode at 0x400c3c (size 48)>, 4197484: <BlockNode at 0x400c6c (size 32)>}`
```
And can a basic block belong to both functions at the same time?

**Comment by ltfish** [comment] 2019-09-04 08:06
This is a bug (and probably a regression because I fixed something similar in the past). Can you please post the binary so it's easier for me to download and fix? Thanks!

**Comment by p611148aadsl** [comment] 2019-09-04 08:12
[binary.zip](https://github.com/angr/angr/files/3573420/binary.zip)

**Comment by ltfish** [comment] 2019-09-15 01:38
> And can a basic block belong to both functions at the same time?

To answer your second question:

```
ipdb> p list(cfg.functions.function(0x400bcc).blocks)
[<Block for 0x400bcc, 4 bytes>]
ipdb> p cfg.functions.function(0x400bcc)._addr_to_block_node
{4197324: <BlockNode at 0x400bcc (size 4)>, 4197328: <BlockNode at 0x400bd0 (size 56)>}
```

`Function._addr_to_block_node` is just a cache. If you want to enumerate all functions in this function, use `.blocks` or `.block_addrs_set` instead.

**Comment by ltfish** [comment] 2019-09-15 01:42
And to answer your original question:

```
ipdb> p cfg.functions[0x400bcc].alignment
True
```

Beginning from https://github.com/angr/angr/commit/a03c6a10c191ffbb0b361b26999759b706b5a94e, alignments are not removed from the CFG anymore. Instead they are marked as `alignment`. It's up to the user to decide what to do with them.

**Closed** 2019-09-15 09:55 UTC
Labels: question
