### ISSUE TITLE
Storage Tuple concat

### ISSUE THREAD

**Issue by Tim-Nosco** [angr/angr#1034] opened 2018-06-08 16:49 UTC
https://github.com/angr/angr/blob/master/angr/storage/file.py#L191
`kwargs['extra_constraints'] = kwargs.get('extra_constraints', ()) + (self._size == size,)`
should be:
`kwargs['extra_constraints'] = kwargs.get('extra_constraints', []) + [self._size == size]`

**Comment by Tim-Nosco** [comment] 2018-06-08 16:50
The error comes when someone passes `extra_constraints` as a list.. which I suppose could be passed as a tuple.. Maybe this is an unnecessary change.

**Comment by Tim-Nosco** [comment] 2018-06-08 16:55
Also to avoid state_plugins/symbolic_memory.py#L325
`raise SimMemoryLimitError("Concrete size %d outside of allowable limits" % i)`
change the line to:
`kwargs['extra_constraints'] = kwargs.get('extra_constraints', []) + [self._size == min(size, _maximum_concrete_size)]

**Comment by rhelmot** [comment] 2018-06-08 20:46
The tuple/list thing is a problem. We can just coerce it into a list and then do the concat as a list.

The latter thing is complicated. The thing you've suggested is confusing because `self._size` doesn't exist, but really it's kind of a moot point because that check is _supposed_ to be an abort condition. If you're really trying to store more than 16MB in a single go, something is _very_ wrong and you should debug the cause instead of trying to make it just work.

**Comment by Tim-Nosco** [comment] 2018-06-13 13:33
I disagree that it is a mute point because size can be symbolic and if unconstrained, a valid size could be maximum_concrete_size.
In my particular program the only symbolic read is just a few bytes (less than 100) and I still hit this raise on line 325.
https://github.com/jakespringer/angr_ctf problem 07_angr_symbolic_file

@rhelmot

**Comment by rhelmot** [comment] 2018-06-13 21:30
That branch can never be reached if the size is symbolic - it's guarded by `if not self.state.solver.symbolic(size)`. It does sound like something is wrong though. Post a binary and an associated script and I'll look at it. I don't have the time to play the angr ctf, unfortunately...

**Comment by Tim-Nosco** [comment] 2018-06-14 14:02
This is the [binary](https://github.com/Tim-Nosco/z3_lessons/blob/master/angr_ctf/07_angr_symbolic_file) (decompilation to follow).
This is the [script](https://github.com/Tim-Nosco/z3_lessons/blob/master/angr_ctf/07_issue.py#L24).
Binary main decompilation to save you time:
```
void main(void)

{
  undefined uVar1;
  int iVar2;
  int local_14;
  
  memset(&buffer,0,0x40);
  printf("Enter the password: ");
  __isoc99_scanf("%64s",&buffer);
  ignore_me(&buffer,0x40);
  memset(&buffer,0,0x40);
  fp = fopen("OJKSQYDP.txt","rb");
  fread(&buffer,1,0x40,fp);
  fclose(fp);
  unlink("OJKSQYDP.txt");
  local_14 = 0;
  while (local_14 < 8) {
    uVar1 = complex_function((int)(char)(&buffer)[local_14],local_14);
    (&buffer)[local_14] = uVar1;
    local_14 = local_14 + 1;
  }
  iVar2 = strncmp(&buffer,"AQWLCTXB",9);
  if (iVar2 != 0) {
    puts("Try again.");
                    /* WARNING: Subroutine does not return */
    exit(1);
  }
  puts("Good Job.");
                    /* WARNING: Subroutine does not return */
  exit(0);
}
```

**Comment by rhelmot** [comment] 2018-06-15 19:41
OH, I understand what you're saying! I thought you were saying this was a problem isolated in SimSymbolicMemory, but you were saying that the change ought to go in the same place the other change should be... Okay, yeah, that's totally reasonable.

This part is a _little_ precarious because of the implicit contract we have that all evaluations of variables will be consistent with each other unless you add more constraints - this will add a constraint so the concretization won't necessarily be consistent with other evaluations that happen. I... don't really see a good way around this, though, unless we actually add the new size as a constraint.

I'm sure if this turns into an issue I'll hear about it.

**Comment by rhelmot** [comment] 2018-06-15 20:35
I pushed two things that make your script work. The first is using `min` to evaluate the filesize instead of `eval`.

The second is a quick hack to make working with unlinked files more convenient. As an optimization, we don't actually deepcopy the unlinked files since nobody can ever mutate them anymore, but it does mean that they're stuck with the state, and thus the constraints, from when they're unlinked. This is easily fixed by just reassociating them with the state you want to solve against, but this is unintuitive. Now, whenever you access `.unlinks`, it'll automatically associate the files with the current state. This will cause problems if you ever pull a reference to a file out of the unlinks list and store it elsewhere, and then try to access a different state's unlinks containing the same file, but that seems relatively uncommon.

**Closed by rhelmot** 2018-06-15 20:35 UTC

**Comment by Tim-Nosco** [comment] 2018-06-22 16:59
Thank you for looking into this!
