### ISSUE TITLE
why i can not unhook __uClibc_main

### ISSUE THREAD

**Issue by yangshouguo** [angr/angr#1782] opened 2019-11-02 08:26 UTC
```
self.project.unhook_symbol("__uClibc_main")
print self.project.is_symbol_hooked("__uClibc_main")
```
The result is True.
Why i can not unhook __uClibc_main

**Comment by fmagin** [comment] 2019-11-02 08:47
Could you provide the binary and script where this happens? This should be fairy easy to find out, but I'd have to find some binary where this happens first.

**Comment by rhelmot** [comment] 2019-11-02 08:50
https://github.com/angr/angr/blob/master/angr/project.py#L542

Unhook symbol is documented to fail intentionally if the unhook operation
would cause there to be no implementation of the library function
available, i.e. if you set auto_load_libs=False

**Comment by yangshouguo** [comment] 2019-11-02 09:21
Thanks for reply.
Here is the code and binaries.
```
import angr
the_libs = ['ld-uClibc.so.0', 'libgcc_s_4181.so.1', 'libc.so.0', 'apmib.so', 'mini_upnp.so', 'libpthread.so.0']
main_opts ={'base_addr': 4194304}
lib_opts ={'ld-uClibc.so.0': {'base_addr': 1987805184},
          'libgcc_s_4181.so.1': {'base_addr': 1986363392},
          'libc.so.0': {'base_addr': 1986678784},
          'apmib.so': {'base_addr': 1987473408},
          'mini_upnp.so': {'base_addr': 1987174400}}
project = angr.Project("boa",
                    use_sim_procedures = False,
                    preload_libs = the_libs,
                    lib_opts = lib_opts,
                    main_opts = main_opts,
                    ignore_import_version_numbers = True,
                    )
project.unhook_symbol("__uClibc_main")
print(project.is_symbol_hooked("__uClibc_main"))
```
[test.zip](https://github.com/angr/angr/files/3800305/test.zip)

**Comment by fmagin** [comment] 2019-11-02 10:18
Can you post the output especially the warnings that you get? For some reason this doesnt work for me and what should be current master. As @rhelmot stated, this is documented and should result in a warning explicitly stating this. If this doesn't show in your case I'd count it as a bug, if it does show the warning it works as intended.

The fact that this might not work for some reason on current master is another issue but that might just be my setup being broken.

**Comment by rhelmot** [comment] 2019-11-04 00:15
Your binaries are super, super fucked up. I can't even load them right now without triggering a totally different bug related to an edge case with relative relocs and SHT_NONE symbols, and when I fix that I see that CLE is totally unable to tell that libc even exports `__uClibc_main`. It's not like I can tell what ground truth is, since readelf completely cannot handle that binary either... I can see that the string `__uClibc_main` appears in strings(1) output, but none of the ELF structures I can crawl through seem to be able to lead to it.

The answer to your original question is exactly what I said in the first place - that since uclibc_main is provided by the extern object in this configuration unhooking it is illegal - but I do not know what it will take to get CLE to load these binaries properly so that uclibc_main is correctly resolved by libc.so.0. Sorry :(

**Comment by yangshouguo** [comment] 2019-11-04 02:03
> Can you post the output especially the warnings that you get? For some reason this doesnt work for me and what should be current master. As @rhelmot stated, this is documented and should result in a warning explicitly stating this. If this doesn't show in your case I'd count it as a bug, if it does show the warning it works as intended.
> 
> The fact that this might not work for some reason on current master is another issue but that might just be my setup being broken.

Sorry for the late reply. I tried unhook the `__uClibc_main` to according to the error message
```
  File "/home/ysg/Desktop/WorkSpace/tracer/test-ysg/angr_conclic.py", line 106, in run
    self.simgr.run()
  File "/usr/local/lib/python3.5/dist-packages/angr/sim_manager.py", line 260, in run
    self.step(stash=stash, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/angr/exploration_techniques/tracer.py", line 225, in step
    return simgr.step(stash=stash, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/angr/misc/hookset.py", line 80, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/angr/sim_manager.py", line 344, in step
    successors = self.step_state(state, successor_func=successor_func, **run_args)
  File "/usr/local/lib/python3.5/dist-packages/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/angr/exploration_techniques/tracer.py", line 275, in step_state
    self._update_state_tracking(succs[0])
  File "/usr/local/lib/python3.5/dist-packages/angr/exploration_techniques/tracer.py", line 433, in _update_state_tracking
    self._fast_forward(state)
  File "/usr/local/lib/python3.5/dist-packages/angr/exploration_techniques/tracer.py", line 576, in _fast_forward
    raise AngrTracerError("Trace failed to synchronize during fast forward? You might want to unhook %s." % (self.project.hooked_by(state.history.addr).display_name)) from e
angr.errors.AngrTracerError: Trace failed to synchronize during fast forward? You might want to unhook __uClibc_main.
```

**Comment by rhelmot** [comment] 2019-11-04 02:06
my response still applies

**Comment by yangshouguo** [comment] 2019-11-04 02:25
> my response still applies

Sorry for the slow reply.  I am trying to find symbol `__uClibc_main` but failed. 
I slightly modified source code in `project.py`, added 
```
            if func and func.name in ["pthread_create"]:
                continue
```
after line 258 `func = reloc.symbol` to pass the error which try to avoid angr loading all symbols which are not needed.

**Comment by yangshouguo** [comment] 2019-11-04 02:28
> > my response still applies
> 
> Sorry for the slow reply. I am trying to find symbol `__uClibc_main` but failed.
> I slightly modified source code in `project.py`, added
> 
> ```
>             if func and func.name in ["pthread_create"]:
>                 continue
> ```
> 
> after line 258 `func = reloc.symbol` to avoid angr loading all symbols which are not needed.

For example, libc.so.0 imported functions about thread but I don't need these functions.

**Comment by rhelmot** [comment] 2019-11-04 02:31
I know... I also had to make a fix like that. The problem is that there is a bug in CLE that the binaries cannot be loaded correctly. I don't know how to fix this because I don't understand the ELF structure of your binaries, which seems to be very nonstandard.

**Comment by yangshouguo** [comment] 2019-11-04 02:48
> I know... I also had to make a fix like that. The problem is that there is a bug in CLE that the binaries cannot be loaded correctly. I don't know how to fix this because I don't understand the ELF structure of your binaries, which seems to be very nonstandard.

Yes, i found it is very unusual. It seems ld.so transformed the control to the address `0x406F20` in boa according to the qeme trace file. The files which i analyzed came from the the router firmware. It is different from the normal ELF binaries. So i encountered many problem. Anyway, thanks very much.

**Comment by yangshouguo** [comment] 2019-11-04 06:55
One more question. If I am using angr.exploration_techniques.Tracer of angr, what can I do to get angr to avoid executing the `__uClibc_main` function or to do it in some other way?

**Comment by fmagin** [comment] 2019-11-04 08:24
You should be able to replace the hook with another custom SimProcedure that only does exactly what you want it to do. It is impossible to _unhook_ the current SimProcedure because then no code would be available, but it is perfectly fine to _replace_ it.

**Comment by yangshouguo** [comment] 2019-11-04 08:40
> Your binaries are super, super fucked up. I can't even load them right now without triggering a totally different bug related to an edge case with relative relocs and SHT_NONE symbols, and when I fix that I see that CLE is totally unable to tell that libc even exports `__uClibc_main`. It's not like I can tell what ground truth is, since readelf completely cannot handle that binary either... I can see that the string `__uClibc_main` appears in strings(1) output, but none of the ELF structures I can crawl through seem to be able to lead to it.
> 
> The answer to your original question is exactly what I said in the first place - that since uclibc_main is provided by the extern object in this configuration unhooking it is illegal - but I do not know what it will take to get CLE to load these binaries properly so that uclibc_main is correctly resolved by libc.so.0. Sorry :(

I think that I kown the reason about ELF can not find symbol `__uClibc_main`. It is because that the file  "libc.so.0" is compiled from ulibc not glibc. So I used the readelf in ulibc to find symbol and it works.
```
./mipsel-buildroot-linux-uclibc-readelf -s -D libc.so.0 | grep main
  367 187: 000246c8   892 FUNC    GLOBAL DEFAULT bad __uClibc_main
```
So maybe the ELF can not handle the binaries from ulibc.

**Comment by rhelmot** [comment] 2019-11-04 08:43
...hold on. this is the information I was missing. I am moderately horrified that uclibc uses an elf format that's completely incompatible with glibc. I will however try to use this information to fix it.

**Comment by yangshouguo** [comment] 2019-11-04 12:20
Please let me know after you fix it.

**Comment by rhelmot** [comment] 2019-12-09 00:19
I was able to fix some bugs in readelf that made the binary render correctly there, but somehow I was unable to reproduce the problems I found with your binaries in angr. They seem to load just fine now, and `__uClibc_main` can be unhooked correctly, though I didn't change anything:

```
[-] In [1]: import angr
       ...: the_libs = ['ld-uClibc.so.0', 'libgcc_s_4181.so.1', 'libc.so.0', 'apmib.so', 'mini_upnp.so', 'libpthread.so.0']
       ...: main_opts ={'base_addr': 4194304}
       ...: lib_opts ={'ld-uClibc.so.0': {'base_addr': 1987805184},
       ...:           'libgcc_s_4181.so.1': {'base_addr': 1986363392},
       ...:           'libc.so.0': {'base_addr': 1986678784},
       ...:           'apmib.so': {'base_addr': 1987473408},
       ...:           'mini_upnp.so': {'base_addr': 1987174400}}
       ...: project = angr.Project("boa",
       ...:                     use_sim_procedures = False,
       ...:                     preload_libs = the_libs,
       ...:                     lib_opts = lib_opts,
       ...:                     main_opts = main_opts,
       ...:                     ignore_import_version_numbers = True,
       ...:                     )

[17:16:40] [cle.loader]              |  WARNING: boa: base_addr was specified but the object is not PIC. specify force_rebase=True to override

[+] In [3]: project.loader.main_object.get_symbol('__uClibc_main').resolvedby
Out[3]: <Symbol "__uClibc_main" in libc.so.0 at 0x766c96c8>

[+] In [4]: project.is_symbol_hooked('__uClibc_main')
Out[4]: False
```

Can you verify that things are less broken than they used to be? If not, can you post your `python -m angr.misc.bug_report`?

**Closed** 2020-10-13 12:13 UTC

**Comment by yangshouguo** [comment] 2020-10-13 12:15
> I was able to fix some bugs in readelf that made the binary render correctly there, but somehow I was unable to reproduce the problems I found with your binaries in angr. They seem to load just fine now, and `__uClibc_main` can be unhooked correctly, though I didn't change anything:
> 
> ```
> [-] In [1]: import angr
>        ...: the_libs = ['ld-uClibc.so.0', 'libgcc_s_4181.so.1', 'libc.so.0', 'apmib.so', 'mini_upnp.so', 'libpthread.so.0']
>        ...: main_opts ={'base_addr': 4194304}
>        ...: lib_opts ={'ld-uClibc.so.0': {'base_addr': 1987805184},
>        ...:           'libgcc_s_4181.so.1': {'base_addr': 1986363392},
>        ...:           'libc.so.0': {'base_addr': 1986678784},
>        ...:           'apmib.so': {'base_addr': 1987473408},
>        ...:           'mini_upnp.so': {'base_addr': 1987174400}}
>        ...: project = angr.Project("boa",
>        ...:                     use_sim_procedures = False,
>        ...:                     preload_libs = the_libs,
>        ...:                     lib_opts = lib_opts,
>        ...:                     main_opts = main_opts,
>        ...:                     ignore_import_version_numbers = True,
>        ...:                     )
> 
> [17:16:40] [cle.loader]              |  WARNING: boa: base_addr was specified but the object is not PIC. specify force_rebase=True to override
> 
> [+] In [3]: project.loader.main_object.get_symbol('__uClibc_main').resolvedby
> Out[3]: <Symbol "__uClibc_main" in libc.so.0 at 0x766c96c8>
> 
> [+] In [4]: project.is_symbol_hooked('__uClibc_main')
> Out[4]: False
> ```
> 
> Can you verify that things are less broken than they used to be? If not, can you post your `python -m angr.misc.bug_report`?

Sorry for late reply. I have not continued that project for a long time.
