### ISSUE TITLE
CFGFast seg faulting on initial analysis

### ISSUE THREAD

**Issue by justinmiller61** [angr/angr#813] opened 2017-12-29 18:01 UTC
While working on the aeg exercise at pwnable.kr, I'm trying to run a CFGFast analysis on the sample binaries and pretty quickly, I'm getting a seg fault. Attached is a sample binary. I'm using version 7.7.12.16 of angr.

Here the snippet of python that generates the seg fault. Pretty straightforward.

```python
import angr

p = angr.Project("aeg", auto_load_libs=True)
cfg = p.analyses.CFGFast(regions=[(p.loader.main_object.min_addr, p.loader.main_object.max_addr)], force_complete_scan=False)
```

[aeg.gz](https://github.com/angr/angr/files/1593637/aeg.gz)

**Comment by rhelmot** [comment] 2017-12-31 05:08
@ltfish this is your bug. in cfg_base.py `_fast_memory_load_bytes` it doesn't check that the memory region it's trying to load... actually exists and can serve the number of contiguous bytes requested.

justin: the issue is caused by your specifying a region that isn't continuously mapped. This is obviously a bug but in the meantime you should pick a better regions argument.

**Comment by ltfish** [comment] 2018-01-02 14:08
This issue should be fixed. Thanks for reporting!

**Closed by ltfish** 2018-01-02 14:08 UTC
