### ISSUE TITLE
 Could not step to the first address of the trace - state split

### ISSUE THREAD

**Issue by lzina** [angr/angr#1544] opened 2019-04-28 11:16 UTC
The binary I am analyzing is Palindrome from CGC binaries. (attached)
[Issue2.zip](https://github.com/angr/angr/files/3127339/Issue2.zip)
(Please put the include files in the right path (as mention below) in order to make it run for you.)

The binary is 32 bit and was compiled with "DARPA Challenges Sets for Linux, Windows, and macOS" => https://github.com/trailofbits/cb-multios

Thte binary runs on system 64 bit and as I understand, there is no problem to run angr with 32 bit binary.

ldd return the list below:

```
        linux-gate.so.1 (0xf7fd1000)
	libcgc.so => /cb-multios/build/include/libcgc.so (0xf7fc7000)
	libtiny-AES128-C.so => /cb-multios/build/include/tiny-AES128-C/libtiny-AES128-C.so (0xf7fc2000)
	libc.so.6 => /lib32/libc.so.6 (0xf7dd0000)
	/lib/ld-linux.so.2 (0xf7fd3000)
```
According to the debug mode:
```
project.loader.shared_objects['libcgc.so'].binary is '/cb-multios/build/include/libcgc.so'
project.loader.shared_objects['libtiny-AES128-C.so'].binary is '/cb-multios/build/include/tiny-AES128-C/libtiny-AES128-C.so'
```
I don't see any reference to libc.so.6

The python test file is:

```
#!/usr/bin/env python

import driller

with open("myfile", "rb") as f:
    bytes_input = f.read()
d = driller.Driller("Palindrome",  # path to the target binary
                    bytes_input  # initial testcase
                    )
new_inputs = d.drill()
print(new_inputs)

```
The error I get is:

```
  Traceback (most recent call last):
  File "/home/glass/PycharmProjects/driller_new/drill_run.py", line 12, in <module>
    new_inputs = d.drill()
  File "/home/glass/PycharmProjects/driller_new/venv/lib/python3.6/site-packages/driller/driller_main.py", line 85, in drill
    list(self._drill_input())
  File "/home/glass/PycharmProjects/driller_new/venv/lib/python3.6/site-packages/driller/driller_main.py", line 131, in _drill_input
    simgr.use_technique(t)
  File "/home/glass/PycharmProjects/driller_new/venv/lib/python3.6/site-packages/angr/sim_manager.py", line 187, in use_technique
    tech.setup(self)
  File "/home/glass/PycharmProjects/driller_new/venv/lib/python3.6/site-packages/angr/exploration_techniques/tracer.py", line 86, in setup
    raise AngrTracerError("Could not step to the first address of the trace - state split")
angr.errors.AngrTracerError: Could not step to the first address of the trace - state split
```

I appreciate your help.
Thanks!

**Comment by rhelmot** [comment] 2019-04-29 18:40
I'll look into this, but you should really just analyze the original cgc binary instead of the trail of bits knockoffs.

**Comment by rhelmot** [comment] 2019-04-29 19:17
So from what I can tell it is indeed because angr has not loaded libc correctly. I believe this would be addressed by https://github.com/angr/archinfo/commit/3eb906fa1f05e6cd8ccc9e5cfc228cf4605f6902, which has been available on github for a few weeks but isn't on pypi yet.

I have also pushed a few changes which make this testcase work much better: 

- https://github.com/angr/angr/commit/378799b1eeee7d0ed626a08e27d6b8bd76f477c0
- https://github.com/angr/angr/commit/7a15e5c3436b4f1c29eccfd971998d7c5ef1b4d7
- https://github.com/shellphish/driller/commit/5ab736700d42fe6f2157d75425d244fd140bcd2a

**Comment by lzina** [comment] 2019-07-07 08:43
> So from what I can tell it is indeed because angr has not loaded libc correctly. I believe this would be addressed by [angr/archinfo@3eb906f](https://github.com/angr/archinfo/commit/3eb906fa1f05e6cd8ccc9e5cfc228cf4605f6902), which has been available on github for a few weeks but isn't on pypi yet.
> 
> I have also pushed a few changes which make this testcase work much better:
> 
> * [378799b](https://github.com/angr/angr/commit/378799b1eeee7d0ed626a08e27d6b8bd76f477c0)
> * [7a15e5c](https://github.com/angr/angr/commit/7a15e5c3436b4f1c29eccfd971998d7c5ef1b4d7)
> * [shellphish/driller@5ab7367](https://github.com/shellphish/driller/commit/5ab736700d42fe6f2157d75425d244fd140bcd2a)

Hi, 
Thanks for the solution. Really helped for the CGC 32-bits binaries.
However when trying to run some known 64-bit on Ubuntu-18 as tcpdump 4.9.2/ tiff2pdf 3.9.7,  I get the error below:
(As I remember, the version of the binaries is not relevant)
```
WARNING | 2019-07-07 11:32:28,903 | cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.
WARNING | 2019-07-07 11:32:32,879 | cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.
Traceback (most recent call last):
  File "/home/glass/PycharmProjects/driller-afl/venv/test_cases/drill_run.py", line 16, in <module>
    new_inputs = d.drill()
  File "/home/glass/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/driller/driller_main.py", line 85, in drill
    list(self._drill_input())
  File "/home/glass/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/driller/driller_main.py", line 131, in _drill_input
    simgr.use_technique(t)
  File "/home/glass/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/sim_manager.py", line 188, in use_technique
    tech.setup(self)
  File "/home/glass/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/exploration_techniques/tracer.py", line 192, in setup
    raise AngrTracerError("Could not step to the first address of the trace - state split")
angr.errors.AngrTracerError: Could not step to the first address of the trace - state split
```
What can be the problem. 
Please your help.

Thanks!!

**Comment by rhelmot** [comment] 2019-07-29 22:48
From my (extremely brief) experimentation, it looks like the problem is that someone in the binary's initializers calls sigaction, and angr doesn't have sigaction implemented, so it returns a symbolic value. Then, the state splits. Because we're in the mode where we're searching for the entry point, angr can't handle the state split.

Technically, the information necessary to follow the trace here does exist, but it's kind of hard to get at because angr will just be calling all the initializers in sequence and the trace will show the loader calling each initializer. We would need to be able to find where each of the initializers is being called in the trace, and use that in order to guide this part of the tracing. I have no idea how to do that in a clean way...

**Comment by rhelmot** [comment] 2021-07-23 06:56
Someone linked this issue, so I figured I would post an update: if you're seeing this thread because you're getting the error in the title, you want to build your tracer object with `Tracer(fast_forward_to_entry=False)`. This will enable the state to execute in trace-following mode while running the shared object initializers.

**Closed by rhelmot** 2021-07-23 06:56 UTC
Labels: bug, enhancement, help wanted
