### ISSUE TITLE
pyvex_c missing

### ISSUE THREAD

**Issue by jimaf** [angr/angr#47] opened 2015-12-15 07:57 UTC
I run pip install angr   and get a warning that pyvex_c can not be found when building pyvex. I believe there is a missing dependency

**Comment by ltfish** [comment] 2015-12-15 07:58
@zardus You might know what's going on.

Let me do a `pip install angr` right now.

**Comment by jimaf** [comment] 2015-12-15 08:12
Using..
pip 1.1 from /usr/lib/python2.7/dist-packages (python 2.7)
 
Linux debian-cgc 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u5 x86_64 GNU/Linux

**Comment by ltfish** [comment] 2015-12-15 08:13
`pip install angr` works for me (on Ubuntu 14.04). You don't need `pyvex_c` if you are installing from PyPI, since we have built the `pyvex_static.so` for you.

If you want to compile `pyvex` on a different system and requires `pyvex_c`, you might want to checkout `pyvex` from https://github.com/angr/pyvex, and perform a manual compilation.

@zardus is the expert, so he should be able to answer this question in depth.

**Comment by rhelmot** [comment] 2015-12-15 08:15
Pip 1.1 is positively ancient and I think we agreed not to support it?

You can get yourself a virtual environment with an up-to-date pip (from the python repos, not debian's) with

`mkvirtualenv angr`, `pip install -U pip`, and then `pip install angr` should have a better chance of success.

**Comment by jimaf** [comment] 2015-12-15 19:18
Thanks.
-Jimaf

--------------------------
Jim Alves-Foss, Director
Center Secure & Dependable Systems
University of Idaho
------

Sent from my Android phone using TouchDown (www.nitrodesk.com)

-----Original Message-----

**Comment by jimaf** [comment] 2015-12-17 00:43
Thanks.

After updating pip,  and upgrading setup tools, and then installing python-dev and other packages as per the README.md in the angr directory; it work. I was trying to follow the instructions in: https://github.com/angr/angr-doc/blob/master/README.md  and this misses the extra packages that need to be installed.

Now that I have it, I will play with it.

-jimaf

**Comment by ltfish** [comment] 2015-12-17 01:38
It's great to know that the problem is solved!

Please close this issue :-)

**Closed** 2016-03-20 07:36 UTC
