### ISSUE TITLE
Angr gives wrong answers

### ISSUE THREAD

**Issue by ikey4u** [angr/angr#939] opened 2018-04-12 10:27 UTC
I follow the tutorial posted here https://ocw.cs.pub.ro/courses/cns/labs/lab-13, when I run the solution "solve.py", angr gives me the following result:
`arg1 = '-2147483073'
arg2 = '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00FLOW'`

I try to use
` ./level07 -2147483073 $(python -c 'print "A"*40 + "FLOW"') ` to test the result, Segmentation fault happens.

`Segmentation fault (core dumped)`

The codes and binary could be downloaded from here:http://elf.cs.pub.ro/oss/res/labs/lab-13.tar.gz

Any suggestions are appreciated!

**Update**
The wrong answer is not related to the character '\x00' or 'A', in fact ,any single character will be ok as long as the length is 40. The main matter is that angr gives a wrong count value -2147483073 rather than the correct value -2147483627. For your convenience, I paste the level07.c source code, makefile and the angr solution here.

**level07.c**

```
#include <stdio.h>
#include <string.h>
#include <unistd.h>

int main(int argc, char **argv)
{
    int count = atoi(argv[1]);
    int buf[10];

    if(count >= 10 )
        return 1;

    memcpy(buf, argv[2], count * sizeof(int));
    if(count == 0x574f4c46) {
        printf("WIN!\n");
    } else
        printf("Not today son\n");

    return 0;
}
```

**makefile**

```
prog=level07.c
out=level07
all:
	gcc ${prog} -o ${out} -fno-stack-protector -m32 -z execstack
```

The makefile above has disabled canary and NX bit and compiles the program in x86 arch.

and the angr solution code is as follow with few modifications.
**angr solution**

```
#! /usr/bin/env python
#! -*- coding:utf-8 -*-
import angr
import claripy

proj = angr.Project('./level07')

arg1 = claripy.BVS('sym_arg', 8 * 11)
arg2 = claripy.BVS('sym_arg', 8 * 44)


init_state = proj.factory.entry_state(args=['./level07', arg1, arg2])
init_state.libc.max_strtol_len = 11


smgr = proj.factory.simgr(init_state)


smgr.explore(find=lambda sm: "WIN" in sm.state.posix.dumps(1))

if (len(smgr.found) > 0):
    sol_state = smgr.found[0]
    print "arg1 = {} ".format(repr(sol_state.se.eval(arg1,cast_to=str)))
    print "arg2 = {} ".format(repr(sol_state.se.eval(arg2,cast_to=str)))
```

**Comment by Alexeyan** [comment] 2018-04-12 15:52
Without checking your links: Why exactly aren't you using
./level07 -2147483073 $(python -c 'print "\x00"*40 + "FLOW"') 

the "A" doesn't make sense here.

**Comment by rhelmot** [comment] 2018-04-12 21:50
Probably because argv is a bunch of null terminated strings... Something is definitely going on here. I’ll take a look at it when I have time.

**Comment by ikey4u** [comment] 2018-04-13 02:49
@Alexeyan Hi, Its no matter what the character is. Any single character is ok. The main matter is that the count value -2147483073 is not correct. The correct value should be -2147483627.

**Comment by ikey4u** [comment] 2018-04-13 03:02
@rhelmot Thank you for your reply. I have updated the question, it is not related to the null terminated strings but the count value.

**Comment by rhelmot** [comment] 2018-04-23 02:44
Yes - I was responding to Alexyan.

I have looked into this. The answer is kind of correct, actually. That specific value you posted doesn't really matter, the only thing that matters is it's negative and will be greater than some small positive number when multiplied by 4. The problem is that angr doesn't understand the relationship between the memcpy size and whether it will cause either the source or destination buffers to segfault. We have a state option for detecting segfaults (STRICT_PAGE_ACCESS), but all that does is cause the memcpy to report that it has the opportunity to segfault (true!) and halt emulation. This could theoretically be fixed by adding a maximum to the buffer sizes based on the memory mapping, but that would prevent angr from being used to find segfaults caused by memcpy...

There are two things you could do in that script to solve this:

1. hook `atoi` to make it return a variable that you control, then evaluate the minimum of that variable. Or... would it be max? I can't remember if min/max use signed or unsigned...
2. tweak the max memcpy limit (state.libc.max_memcpy_size) to be small enough that it doesn't segfault. 500 worked for me

**Comment by zardus** [comment] 2018-04-23 02:48
The solver min/max functions should currently return unsigned values, iirc.

**Comment by Kyle-Kyle** [comment] 2018-05-28 15:10
I did no change to your code. And it gave me the correct answer `-2147483615`

**Comment by Kyle-Kyle** [comment] 2018-05-28 15:13
@rhelmot The value does matter, this problem involves an overflow. It is supposed to overwrite the `count` variable.

**Comment by Kyle-Kyle** [comment] 2018-05-28 15:14
No. I did something to your code. I inserted a line
~~~
init_state.solver.add(arg2 < 0x80000000)
~~~
after `init_state = proj.factory.entry_state(args=['./level07', arg1, arg2])`
And then everything works like a charm.

**Closed** 2018-07-30 02:14 UTC
