### ISSUE TITLE
Windows Z3 has no attribute "set_param"

### ISSUE THREAD

**Issue by WittsEnd2** [angr/angr#2865] opened 2021-08-14 20:10 UTC
---

**Describe the bug.**

When importing angr on Windows, I always get this error from the Traceback:

```
Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import angr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\micha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\angr\__init__.py", line 30, in <module>
    from .sim_procedure import SimProcedure
  File "C:\Users\micha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\angr\sim_procedure.py", line 6, in <module>
    from cle import SymbolType
  File "C:\Users\micha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\cle\__init__.py", line 18, in <module>
    from .loader import *
  File "C:\Users\micha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\cle\loader.py", line 15, in <module>
    import claripy
  File "C:\Users\micha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\claripy\__init__.py", line 21, in <module>
    from . import backends as _backends_module
  File "C:\Users\micha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\claripy\backends\__init__.py", line 771, in <module>
    from .backend_z3 import BackendZ3
  File "C:\Users\micha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\claripy\backends\backend_z3.py", line 56, in <module>
    z3.set_param('rewriter.hi_fp_unspecified', 'true')
AttributeError: module 'z3' has no attribute 'set_param'
```
**Environment Information.**

Windows 10 20H2 - Can't do `python -m angr.misc.bug_report` due to angr import issues mentioned above. 

**To Reproduce.**

Just import angr on Python 3 environment in Windows. 

**Additional context.**

**Comment by ltfish** [comment] 2021-08-14 23:34
Can you run this for me:

```
python -c "import z3; print(z3.__file__)"
```

**Comment by WittsEnd2** [comment] 2021-08-15 00:12
Here is the result from it: 
```
C:\
λ python3 -c "import z3; print(z3.__file__)
C:\Users\micha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\z3\__init__.py
```

**Comment by ltfish** [comment] 2021-08-15 01:02
Can you take a look at `C:\Users\micha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\z3\z3.py` and see if there is a `set_param` method inside?

I have no idea of what is going on. My only guess is that you are using the right z3 package for some reason.

**Comment by WittsEnd2** [comment] 2021-08-15 01:54
yeah, I am not sure either. It looks like there is one in `z3.py`

```py
def set_param(*args, **kws):
    """Set Z3 global (or module) parameters.

    >>> set_param(precision=10)
    """
    if z3_debug():
        _z3_assert(len(args) % 2 == 0, "Argument list must have an even number of elements.")
    new_kws = {}
    for k in kws:
        v = kws[k]
        if not set_pp_option(k, v):
            new_kws[k] = v
    for key in new_kws:
        value = new_kws[key]
        Z3_global_param_set(str(key).upper(), _to_param_value(value))
    prev = None
    for a in args:
        if prev is None:
            prev = a
        else:
            Z3_global_param_set(str(prev), _to_param_value(a))
            prev = None
```

I have a feeling this is my own system being wonky.

**Comment by ltfish** [comment] 2021-08-16 17:47
If you can install IPython, after importing angr in IPython, you can run `%debug` to get an ipdb shell at the location where that exception is raised. Take a look at `z3` to see if it is the same z3 module as we would expect (`z3.__class__`, `z3.__class__.__file__`, and `dir(z3)`).

**Comment by Stolas** [comment] 2022-04-02 09:47
I had the samen issue so I ran the commands.
```
AttributeError: module 'z3' has no attribute 'set_param'

In [2]: %debug
> c:\users\stolas\appdata\local\programs\python\python39\lib\site-packages\claripy\backends\backend_z3.py(56)<module>()
     54
     55 # as of z3 4.8.7.0 this seems to matter
---> 56 z3.set_param('rewriter.hi_fp_unspecified', 'true')
     57
     58 #

ipdb> z3.__class__
<class 'module'>
ipdb> z3.__class__.__file__
*** AttributeError: type object 'module' has no attribute '__file__'
ipdb> dir(z3)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
ipdb>
```

**Comment by ltfish** [comment] 2022-04-02 10:04
Can you run `z3.__file__` or `z3.__path__`? @Stolas

**Comment by Stolas** [comment] 2022-04-02 10:06
```
ipdb> print(z3.__file__)
C:\Users\Stolas\AppData\Roaming\Python\Python39\site-packages\z3\__init__.py
ipdb> print(z3.__path__)
['C:\\Users\\Stolas\\AppData\\Roaming\\Python\\Python39\\site-packages\\z3']
ipdb>
```

**Comment by ltfish** [comment] 2022-04-02 11:23
I have a feeling that it's caused by you using the default Python coming with Windows. What if you install Python by yourself, and then create a virtual environment, and install angr and z3 inside?

Note that I don't think this is an angr problem. If any, it's a Z3 problem or the default Python in Windows problem.

**Comment by Stolas** [comment] 2022-04-02 11:35
I _assume_ angr installs `z3`, instead of `z3-solver` on Windows.
```
λ pip uninstall z3
λ pip install z3-solver
```

Solved it, something for the FAQ?

**Comment by rhelmot** [comment] 2022-04-02 19:12
we never touch the package named `z3`, you almost certainly had it installed for some other reason.

**Comment by Stolas** [comment] 2022-04-02 19:18
Haha, lol could be.
Something for the FAQ, I recommend to close this issue.

**Closed** 2022-04-02 19:33 UTC
Labels: question
