### ISSUE TITLE
Symbion example not working

### ISSUE THREAD

**Issue by alejoseb** [angr/angr#1892] opened 2019-12-26 20:57 UTC
Hi, I am trying to reproduce the Symbion example for x86_64 elf. The example running under the angr-dev environment crashed. I am working on master branches of angr and angr-targets.

**This is the call stack:**

Traceback (most recent call last):
  File "/home/alejandro/Documents/angr-dev/angr/angr/misc/plugins.py", line 245, in request_plugin
    return self._default_plugins[name]
KeyError: 'timeout'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alejandro/Documents/angr-dev/angr/angr/misc/plugins.py", line 71, in __getattr__
    return self.get_plugin(name)
  File "/home/alejandro/Documents/angr-dev/angr/angr/sim_state.py", line 355, in get_plugin
    return super(SimState, self).get_plugin(name)
  File "/home/alejandro/Documents/angr-dev/angr/angr/misc/plugins.py", line 155, in get_plugin
    plugin_cls = self._active_preset.request_plugin(name)
  File "/home/alejandro/Documents/angr-dev/angr/angr/misc/plugins.py", line 247, in request_plugin
    raise AngrNoPluginError("There is no plugin named %s" % name)
angr.errors.AngrNoPluginError: There is no plugin named timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alejandro/Documents/avatar2/tests/symbionx86.py", line 42, in <module>
    exploration = simgr.run()
  File "/home/alejandro/Documents/angr-dev/angr/angr/sim_manager.py", line 260, in run
    self.step(stash=stash, **kwargs)
  File "/home/alejandro/Documents/angr-dev/angr/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/home/alejandro/Documents/angr-dev/angr/angr/exploration_techniques/symbion.py", line 50, in step
    return simgr.step(stash=stash, **kwargs)
  File "/home/alejandro/Documents/angr-dev/angr/angr/misc/hookset.py", line 80, in __call__
    return self.func(*args, **kwargs)
  File "/home/alejandro/Documents/angr-dev/angr/angr/sim_manager.py", line 344, in step
    successors = self.step_state(state, successor_func=successor_func, **run_args)
  File "/home/alejandro/Documents/angr-dev/angr/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/home/alejandro/Documents/angr-dev/angr/angr/exploration_techniques/symbion.py", line 60, in step_state
    if new_state[0].timeout:
  File "/home/alejandro/Documents/angr-dev/angr/angr/misc/plugins.py", line 73, in __getattr__
    raise AttributeError(name)
AttributeError: timeout

**This is my python -m angr.misc.bug_report:**
/home/alejandro/.virtualenvs/angr/lib/python3.7/site-packages/pysmt/walkers/generic.py:43: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if len(nodetypes) == 1 and isinstance(nodetypes[0], collections.Iterable):
angr environment report

Date: 2019-12-26 13:47:37.933984
Running in virtual environment at /home/alejandro/.virtualenvs/angr
Platform: linux-x86_64
Python version: 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0]
######## angr #########
Python found it in /home/alejandro/Documents/angr-dev/angr/angr
Pip version angr 8.19.10.30
Git info:
        Current commit 52c7e640e30a6515a628ac446532fd6b95e2ddd4 from branch master
        Checked out from remote origin: https://github.com/angr/angr
######## ailment #########
Python found it in /home/alejandro/Documents/angr-dev/ailment/ailment
Pip version ailment 8.19.10.30
Git info:
        Current commit 63aa070736eaf38a15f820d82763cf1314201a53 from branch master
        Checked out from remote origin: https://github.com/angr/ailment
######## cle #########
Python found it in /home/alejandro/Documents/angr-dev/cle/cle
Pip version cle 8.19.10.30
Git info:
        Current commit 71ea91e2e6f1e67ec09f8b6e8399ac72c359d464 from branch master
        Checked out from remote origin: https://github.com/angr/cle
######## pyvex #########
Python found it in /home/alejandro/Documents/angr-dev/pyvex/pyvex
Pip version pyvex 8.19.10.30
Git info:
        Current commit 99f2d0afab49d99ff17f9555ce2e8e0993ec8ca9 from branch master
        Checked out from remote origin: https://github.com/angr/pyvex
######## claripy #########
Python found it in /home/alejandro/Documents/angr-dev/claripy/claripy
Pip version claripy 8.19.10.30
Git info:
        Current commit 1a5e0ca61d3f480e541226f103900e983f025e4a from branch master
        Checked out from remote origin: https://github.com/angr/claripy
######## archinfo #########
Python found it in /home/alejandro/Documents/angr-dev/archinfo/archinfo
Pip version archinfo 8.19.10.30
Git info:
        Current commit 98ab35114a1fe4068de03cf073759ede5b0feb7c from branch master
        Checked out from remote origin: https://github.com/angr/archinfo
######## z3 #########
Python found it in /home/alejandro/.virtualenvs/angr/lib/python3.7/site-packages/z3
Pip version z3-solver 4.8.7.0
Couldn't find git info
######## unicorn #########
Python found it in /home/alejandro/.virtualenvs/angr/lib/python3.7/site-packages/unicorn
Pip version unicorn 1.0.1
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/alejandro/Documents/angr-dev/angr/angr/lib/angr_native.so', handle 55ee3c84f8d0 at 0x7eff390cbe10>
unicorn: <CDLL '/home/alejandro/.virtualenvs/angr/lib/python3.7/site-packages/unicorn/lib/libunicorn.so', handle 55ee3bffe050 at 0x7eff3e91ca50>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7eff3f65b410>
z3: <CDLL '/home/alejandro/.virtualenvs/angr/lib/python3.7/site-packages/z3/lib/libz3.so', handle 55ee3c23c4a0 at 0x7eff3c25e8d

**Comment by MrT3acher** [comment] 2020-04-18 18:27
I have the same problem!
```
/usr/local/lib/python3.7/dist-packages/pysmt/walkers/generic.py:43: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  if len(nodetypes) == 1 and isinstance(nodetypes[0], collections.Iterable):
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/angr/misc/plugins.py", line 245, in request_plugin
    return self._default_plugins[name]
KeyError: 'timeout'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/angr/misc/plugins.py", line 71, in __getattr__
    return self.get_plugin(name)
  File "/usr/local/lib/python3.7/dist-packages/angr/sim_state.py", line 355, in get_plugin
    return super(SimState, self).get_plugin(name)
  File "/usr/local/lib/python3.7/dist-packages/angr/misc/plugins.py", line 155, in get_plugin
    plugin_cls = self._active_preset.request_plugin(name)
  File "/usr/local/lib/python3.7/dist-packages/angr/misc/plugins.py", line 247, in request_plugin
    raise AngrNoPluginError("There is no plugin named %s" % name)
angr.errors.AngrNoPluginError: There is no plugin named timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "angrscript.py", line 29, in <module>
    simgr.run()
  File "/usr/local/lib/python3.7/dist-packages/angr/sim_manager.py", line 260, in run
    self.step(stash=stash, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/angr/exploration_techniques/symbion.py", line 50, in step
    return simgr.step(stash=stash, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/angr/misc/hookset.py", line 80, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/angr/sim_manager.py", line 344, in step
    successors = self.step_state(state, successor_func=successor_func, **run_args)
  File "/usr/local/lib/python3.7/dist-packages/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/angr/exploration_techniques/symbion.py", line 60, in step_state
    if new_state[0].timeout:
  File "/usr/local/lib/python3.7/dist-packages/angr/misc/plugins.py", line 73, in __getattr__
    raise AttributeError(name)
AttributeError: timeout
```

**Comment by degrigis** [comment] 2020-05-07 00:39
Uhm, I've missed this, will look into this ASAP!

**Comment by degrigis** [comment] 2020-05-07 05:21
Can you guys share with me the angr script you are using? I can't reproduce it.

**Comment by MrT3acher** [comment] 2020-05-07 19:42
```
import angr
from angr_targets.targets.avatar_gdb import AvatarGDBConcreteTarget
import avatar2
import subprocess

GDB_SERVER_IP = '127.0.0.1'
GDB_SERVER_PORT = 9876

SPOINT = 0x4006d4 # I want execute concretely until this point and then continue symbolic 
FIND = (0x40091b, )
AVOID = (0x400927, )
binary_x64 = './reee'

# Spawning of the gdbserver analysis environment
print("gdbserver %s:%s %s" % (GDB_SERVER_IP,GDB_SERVER_PORT,binary_x64))
subprocess.Popen("gdbserver %s:%s %s" % (GDB_SERVER_IP,GDB_SERVER_PORT,binary_x64),
                  stdout=subprocess.PIPE,
                  stderr=subprocess.PIPE,
                  shell=True)

# Instantiating the ConcreteTarget
avatar_gdb = AvatarGDBConcreteTarget(avatar2.archs.x86.X86_64, GDB_SERVER_IP, GDB_SERVER_PORT)

# Creating the Project
p = angr.Project(binary_x64, concrete_target=avatar_gdb,
                             use_sim_procedures=True)

# Create the state at the beginning of the program
es = p.factory.entry_state()
#es.optinos.add(angr.options.unicorn)

# another problem: there is no SYMBION_SYNC_CLE and SYMBION_KEEP_STUBS_ON_SYNC option
#es.options.add(angr.options.SYMBION_SYNC_CLE) 
#es.options.add(angr.options.SYMBION_KEEP_STUBS_ON_SYNC)

# Create a simulation manager to hold this exploration
simgr = p.factory.simgr(es)

# Explore the program concretely until we reach SPOINT
tech = angr.exploration_techniques.Symbion(find=[SPOINT], timeout = 10)
simgr.use_technique(tech)
exp = simgr.run()
```

**Comment by degrigis** [comment] 2020-05-07 19:58
Uhm, it works for me tho
```
ipdb> exp                                                                                                                                                                                                        
<SimulationManager with 1 found>
ipdb> exp["found"]                                                                                                                                                                                               ipdb> exp.stashes["found"]                                                                                                                                                                                       
[<SimState @ 0x4006d4>]
```
are you on the latest angr? (install it from angr-dev)

**Comment by degrigis** [comment] 2020-05-07 20:01
I really think you don't have the latest angr, the options you are missing are there https://github.com/angr/angr/blob/c5e881d4635b704519363c6d5afc9a5b98b9b9bc/angr/sim_options.py#L299 
:)

**Comment by MrT3acher** [comment] 2020-05-07 20:32
I've used `pip3 install angr -U` to upgrade angr.

**Comment by ltfish** [comment] 2020-05-07 20:33
We haven't published a new version of angr to PyPI for a while. While we will find time to do so, you should switch to the master branch of angr on GitHub for now.

**Comment by degrigis** [comment] 2020-05-07 21:11
Exactly. Try with angr-dev and tell me if you are good so I can close the issue :)

**Closed** 2020-05-08 17:30 UTC
