### ISSUE TITLE
Some errors happened when using the reaching definition method.

### ISSUE THREAD

**Issue by AsaYu2019** [angr/angr#2554] opened 2021-03-09 04:38 UTC
---

**Describe the bug.**

```
>>> proj=angr.Project('a.out')
>>> cfg =proj.analyses.CFGEmulated()
>>> func = cfg.kb.functions.function(addr=0x400526)
>>> proj.analyses.ReachingDefinitions(subject=func, observation_points=[(0x400526, 1)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.virtualenvs/angr3/lib/python3.6/site-packages/angr/analyses/analysis.py", line 115, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/user/.virtualenvs/angr3/lib/python3.6/site-packages/angr/analyses/reaching_definitions/reaching_definitions.py", line 138, in __init__
    self._analyze()
  File "/home/user/.virtualenvs/angr3/lib/python3.6/site-packages/angr/analyses/forward_analysis/forward_analysis.py", line 221, in _analyze
    self._analysis_core_graph()
  File "/home/user/.virtualenvs/angr3/lib/python3.6/site-packages/angr/analyses/forward_analysis/forward_analysis.py", line 240, in _analysis_core_graph
    changed, output_state = self._run_on_node(n, job_state)
  File "/home/user/.virtualenvs/angr3/lib/python3.6/site-packages/angr/analyses/reaching_definitions/reaching_definitions.py", line 339, in _run_on_node
    dep_graph=self._dep_graph,
  File "/home/user/.virtualenvs/angr3/lib/python3.6/site-packages/angr/analyses/reaching_definitions/engine_vex.py", line 56, in process
    block=kwargs.pop('block', None),
  File "/home/user/.virtualenvs/angr3/lib/python3.6/site-packages/angr/engines/light/engine.py", line 85, in _process
    self._process_Stmt(whitelist=whitelist)
  File "/home/user/.virtualenvs/angr3/lib/python3.6/site-packages/angr/engines/light/engine.py", line 106, in _process_Stmt
    self._handle_Stmt(stmt)
  File "/home/user/.virtualenvs/angr3/lib/python3.6/site-packages/angr/analyses/reaching_definitions/engine_vex.py", line 96, in _handle_Stmt
    super(SimEngineRDVEX, self)._handle_Stmt(stmt)
  File "/home/user/.virtualenvs/angr3/lib/python3.6/site-packages/angr/engines/light/engine.py", line 134, in _handle_Stmt
    getattr(self, handler)(stmt)
  File "/home/user/.virtualenvs/angr3/lib/python3.6/site-packages/angr/analyses/reaching_definitions/engine_vex.py", line 140, in _handle_Store
    self._store_core(addr, size, data)
  File "/home/user/.virtualenvs/angr3/lib/python3.6/site-packages/angr/analyses/reaching_definitions/engine_vex.py", line 183, in _store_core
    .get_all_nodes(self._codeloc().ins_addr, anyaddr=True)[0]
IndexError: list index out of range
>>> proj.analyses.ReachingDefinitions(subject=func, observation_points=[(0x400526, 1)], init_func=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.virtualenvs/angr3/lib/python3.6/site-packages/angr/analyses/analysis.py", line 115, in __call__
    oself.__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'init_func'
>>> proj.analyses.ReachingDefinitions(subject=func, observation_points=[(0x400526, 1)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.virtualenvs/angr3/lib/python3.6/site-packages/angr/analyses/analysis.py", line 115, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/user/.virtualenvs/angr3/lib/python3.6/site-packages/angr/analyses/reaching_definitions/reaching_definitions.py", line 138, in __init__
    self._analyze()
  File "/home/user/.virtualenvs/angr3/lib/python3.6/site-packages/angr/analyses/forward_analysis/forward_analysis.py", line 221, in _analyze
    self._analysis_core_graph()
  File "/home/user/.virtualenvs/angr3/lib/python3.6/site-packages/angr/analyses/forward_analysis/forward_analysis.py", line 240, in _analysis_core_graph
    changed, output_state = self._run_on_node(n, job_state)
  File "/home/user/.virtualenvs/angr3/lib/python3.6/site-packages/angr/analyses/reaching_definitions/reaching_definitions.py", line 339, in _run_on_node
    dep_graph=self._dep_graph,
  File "/home/user/.virtualenvs/angr3/lib/python3.6/site-packages/angr/analyses/reaching_definitions/engine_vex.py", line 56, in process
    block=kwargs.pop('block', None),
  File "/home/user/.virtualenvs/angr3/lib/python3.6/site-packages/angr/engines/light/engine.py", line 85, in _process
    self._process_Stmt(whitelist=whitelist)
  File "/home/user/.virtualenvs/angr3/lib/python3.6/site-packages/angr/engines/light/engine.py", line 106, in _process_Stmt
    self._handle_Stmt(stmt)
  File "/home/user/.virtualenvs/angr3/lib/python3.6/site-packages/angr/analyses/reaching_definitions/engine_vex.py", line 96, in _handle_Stmt
    super(SimEngineRDVEX, self)._handle_Stmt(stmt)
  File "/home/user/.virtualenvs/angr3/lib/python3.6/site-packages/angr/engines/light/engine.py", line 134, in _handle_Stmt
    getattr(self, handler)(stmt)
  File "/home/user/.virtualenvs/angr3/lib/python3.6/site-packages/angr/analyses/reaching_definitions/engine_vex.py", line 140, in _handle_Store
    self._store_core(addr, size, data)
  File "/home/user/.virtualenvs/angr3/lib/python3.6/site-packages/angr/analyses/reaching_definitions/engine_vex.py", line 183, in _store_core
    .get_all_nodes(self._codeloc().ins_addr, anyaddr=True)[0]
IndexError: list index out of range
>>> proj.analyses.ReachingDefinitions(subject=func, observation_points=[(0x400526, 1)])
```

**Environment Information.**

angr environment report
=============================
Date: 2021-03-08 22:40:48.709983
Running in virtual environment at /home/asayu/angr
Platform: linux-x86_64
Python version: 3.8.2 (default, Jan 30 2021, 23:58:46) 
[GCC 5.4.0 20160609]
######## angr #########
Python found it in /home/asayu/angr/lib/python3.8/site-packages/angr
Pip version angr 9.0.5610
Git info:
	Current commit 6292a8398ee7a7b5cd98e1e1136168d5d3b874e0 from branch master
Could not resolve tracking branch or remote info!
######## ailment #########
Python found it in /home/asayu/angr/lib/python3.8/site-packages/ailment
Pip version ailment 9.0.5610
Git info:
	Current commit 6292a8398ee7a7b5cd98e1e1136168d5d3b874e0 from branch master
Could not resolve tracking branch or remote info!
######## cle #########
Python found it in /home/asayu/angr/lib/python3.8/site-packages/cle
Pip version cle 9.0.5610
Git info:
	Current commit 6292a8398ee7a7b5cd98e1e1136168d5d3b874e0 from branch master
Could not resolve tracking branch or remote info!
######## pyvex #########
Python found it in /home/asayu/angr/lib/python3.8/site-packages/pyvex
Pip version pyvex 9.0.5610
Git info:
	Current commit 6292a8398ee7a7b5cd98e1e1136168d5d3b874e0 from branch master
Could not resolve tracking branch or remote info!
######## claripy #########
Python found it in /home/asayu/angr/lib/python3.8/site-packages/claripy
Pip version claripy 9.0.5610
Git info:
	Current commit 6292a8398ee7a7b5cd98e1e1136168d5d3b874e0 from branch master
Could not resolve tracking branch or remote info!
######## archinfo #########
Python found it in /home/asayu/angr/lib/python3.8/site-packages/archinfo
Pip version archinfo 9.0.5610
Git info:
	Current commit 6292a8398ee7a7b5cd98e1e1136168d5d3b874e0 from branch master
Could not resolve tracking branch or remote info!
######## z3 #########
Python found it in /home/asayu/angr/lib/python3.8/site-packages/z3
Pip version z3-solver 4.8.10.0
Git info:
	Current commit 6292a8398ee7a7b5cd98e1e1136168d5d3b874e0 from branch master
Could not resolve tracking branch or remote info!
######## unicorn #########
Python found it in /home/asayu/angr/lib/python3.8/site-packages/unicorn
Pip version unicorn 1.0.2rc4
Git info:
	Current commit 6292a8398ee7a7b5cd98e1e1136168d5d3b874e0 from branch master
Could not resolve tracking branch or remote info!
######### Native Module Info ##########
angr: <CDLL '/home/asayu/angr/lib/python3.8/site-packages/angr/lib/angr_native.so', handle 30ae3e0 at 0x7f4fee976c10>
unicorn: <CDLL '/home/asayu/angr/lib/python3.8/site-packages/unicorn/lib/libunicorn.so', handle 27f7ea0 at 0x7f4ff52dd160>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f4ff6462070>
z3: <CDLL '/home/asayu/angr/lib/python3.8/site-packages/z3/lib/libz3.so', handle 2a5b100 at 0x7f4ff2459bb0>

**To Reproduce.**

**Additional context.**

**Comment by mahaloz** [comment] 2021-03-10 20:15
This is a duplicate of https://github.com/angr/angr/issues/2546

**Closed** 2021-03-10 21:49 UTC
Labels: duplicate
