### ISSUE TITLE
SyntaxWarning is emitted over using is for comparison of literals in Python 3.8

### ISSUE THREAD

**Issue by tirkarthi** [angr/angr#1929] opened 2020-01-19 12:43 UTC
**Describe the bug.**

`SyntaxWarning` is emitted over using `is` for comparison of literals.

```
./angr/storage/pcap.py:28: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if myip is self.ip and tcp.dport is self.port and len(tcp.data) is not 0:
./angr/storage/pcap.py:30: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  elif len(tcp.data) is not 0:
./angr/storage/pcap.py:40: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.pos is 0:
```

**Environment Information.**

* Python 3.8

**To Reproduce.**

To compile for the warnings

```
find . -iname '*.py' | xargs -P 4 -I{} python3.8 -Wall -m py_compile {}
```

**Comment by serhiy-storchaka** [comment] 2020-01-19 17:43
The compiler warns about `is` with literals, but other uses of `is`, like in `myip is self.ip` and `tcp.dport is self.port` can also be bugs.

**Comment by rhelmot** [comment] 2020-01-19 19:43
This was fixed in https://github.com/angr/angr/pull/1919.

Furthermore the second comment is extremely not a bug. Those are comparisons between claripy ASTs, which are designed so that objects with identical structure share object identity. This is an optimization called "hash consing".

**Closed by rhelmot** 2020-01-19 19:43 UTC
