### ISSUE TITLE
angr/exploration_techniques/threading.py occured an error

### ISSUE THREAD

**Issue by DreamingD** [angr/angr#1104] opened 2018-07-03 02:05 UTC
Line 32 "tsimgr = simgr.copy(stashes=dict(simgr.stashes))"report an error.The error description is "TypeError: copy() got an unexpected keyword argument 'stashes'.There was no such error a few months ago.Would you help me solve this problem?

**Comment by rhelmot** [comment] 2018-07-03 02:06
Duplicate of #1032. Threading is broken right now.

cc, @danse-macabre

**Closed by rhelmot** 2018-07-03 02:06 UTC
