### ISSUE TITLE
angr 9.2.6 requires unicorn==1.0.2rc4, but you have unicorn 2.0.0rc7 which is incompatible.

### ISSUE THREAD

**Issue by KA2010** [angr/angr#3379] opened 2022-06-07 20:10 UTC
Hi,
Is there is any way that I can make angr work with the latest unicorn? "note that I need unicorn 2"
I appreciate any suggestion or advice!

**Comment by rhelmot** [comment] 2022-06-07 20:11
This is something we want to do, but there have been numerous problems that have come up every time we have tried.

See https://github.com/angr/angr/issues/2541 and https://github.com/angr/angr/pull/3298

**Comment by KA2010** [comment] 2022-06-07 20:47
Thanks for your replay, 
what if I just import static analysis features from angr, "I do not need the unicorn inside angr" Is that possible ?

**Comment by twizmwazin** [comment] 2022-06-07 20:55
If you can get pip to allow you to install angr with the incorrect unicorn version, I would expect anything that doesn't explicitly use unicorn to work. At some point I'm hoping to make the dependency optional.

**Comment by KA2010** [comment] 2022-06-07 21:28
> If you can get pip to allow you to install angr with the incorrect unicorn version, I would expect anything that doesn't explicitly use unicorn to work. At some point I'm hoping to make the dependency optional.
How to get this pip to allow me to install angr with the incorrect unicorn version?
for second part, yes I agree that will good.

**Comment by KA2010** [comment] 2022-06-07 21:29
How to get this pip to allow me to install angr with the incorrect unicorn version?
for second part, yes I agree that will good.

**Comment by KA2010** [comment] 2022-06-07 22:05
What I am looking for from angr is solver engine like Claripy.

**Comment by KA2010** [comment] 2022-06-07 22:06
> Have a look at the `--no-deps` and `--ignore-installed` flags in pip.

I will look at that.

**Comment by twizmwazin** [comment] 2022-06-07 22:27
> What I am looking for from angr is solver engine like Claripy.

You can install the claripy package without angr, which has much fewer dependencies.

**Comment by mustakimur** [comment] 2022-06-08 15:29
@twizmwazin Do you from which angr release, the unicorn becomes compulsory?

**Comment by twizmwazin** [comment] 2022-06-08 16:32
> @twizmwazin Do you from which angr release, the unicorn becomes compulsory?

It has been required for years, this is not the result of a recent change.

**Comment by twizmwazin** [comment] 2022-06-17 23:23
Closing as duplicate of #2541

**Closed by twizmwazin** 2022-06-17 23:23 UTC
