### ISSUE TITLE
angr native crashes due to basic block boundary mismatch between VEX and unicorn

### ISSUE THREAD

**Issue by drvink** [angr/angr#2610] opened 2021-04-21 00:00 UTC
@dnivra OK, here's the new thread.

The [binary I mentioned](https://sicstus.sics.se/sicstus/products4/sicstus/4.6.0/binaries/linux/sp-4.6.0-x86_64-linux-glibc2.17.tar.gz) in #2604 will cause angr to crash every time. It will probably crash even without a demo/license key (you can run the installer with `--nolicense`), but you can also get a demo key [here](https://sicstus.sics.se/eval.html) (it will be immediately emailed to you).

Use the following script:

```
#!/usr/bin/env pypy3

import io, itertools, logging, os, re, sys
import angr # type: ignore
import claripy # type: ignore

try: from typing import Final
except ImportError: pass

INSTALL_PATH = '/usr/local/sicstus4.6.0' # type: Final
BIN_PATH = os.path.join(INSTALL_PATH, 'bin', 'sicstus') # type: Final

proj = angr.Project(BIN_PATH)
st = proj.factory.entry_state(
    args=[proj.filename, '-i', '-m', '--goal', 'halt.'],
    env=os.environ,
    add_options=angr.options.unicorn)
sm = proj.factory.simgr(st)

syms = {
    x : proj.loader.find_symbol(x) for x in ('exit', 'wam_main')
} # type: Final

def main(): # type: () -> None
    sm.explore(find=syms['wam_main'].rebased_addr,
               avoid=syms['exit'].rebased_addr)

if __name__ == '__main__':
    main()
```

`python -m angr.misc.bug_report` output:

```
angr environment report
=============================
Date: 2021-04-21 08:55:59.621989
Running in virtual environment at /home/mdl/prog/angr
Platform: linux-x86_64
Python version: 3.7.10 (51efa818fd9b24f625078c65e8e2f6a5ac24d572, Apr 11 2021, 13:25:22)
[PyPy 7.3.4 with GCC 10.2.0]
######## angr #########
Python found it in /home/mdl/prog/src/angr-dev/angr/angr
Pip version angr 9.0.gitrolling
Git info:
        Current commit 62ed691030504e5af0f192d65f24d59b4fbbd378 from branch master
        Checked out from remote origin: https://github.com/angr/angr.git
######## ailment #########
Python found it in /home/mdl/prog/src/angr-dev/ailment/ailment
Pip version ailment 9.0.gitrolling
Git info:
        Current commit 41a2a34fd1de5339c8fed29329cf5462d41722fd from branch master
        Checked out from remote origin: https://github.com/angr/ailment.git
######## cle #########
Python found it in /home/mdl/prog/src/angr-dev/cle/cle
Pip version cle 9.0.gitrolling
Git info:
        Current commit e027a28b27791246494a6ae5b4c995857485895d from branch master
        Checked out from remote origin: https://github.com/angr/cle.git
######## pyvex #########
Python found it in /home/mdl/prog/src/angr-dev/pyvex/pyvex
Pip version pyvex 9.0.gitrolling
Git info:
        Current commit ff7e97766b889c5e258dbd0034473aa89ff81259 from branch master
        Checked out from remote origin: https://github.com/angr/pyvex.git
######## claripy #########
Python found it in /home/mdl/prog/src/angr-dev/claripy/claripy
Pip version claripy 9.0.gitrolling
Git info:
        Current commit e84355f64bfbb802715872a2b88fea84362fd37e from branch master
        Checked out from remote origin: https://github.com/angr/claripy.git
######## archinfo #########
Python found it in /home/mdl/prog/src/angr-dev/archinfo/archinfo
Pip version archinfo 9.0.gitrolling
Git info:
        Current commit 437b194538ccb0bf118b4b674613b88832b0b342 from branch master
        Checked out from remote origin: https://github.com/angr/archinfo.git
######## z3 #########
Python found it in /home/mdl/prog/angr/site-packages/z3
Pip version z3-solver 4.8.10.0
Couldn't find git info
######## unicorn #########
Python found it in /home/mdl/prog/angr/site-packages/unicorn
Pip version unicorn 1.0.2rc4
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/mdl/prog/src/angr-dev/angr/angr/lib/angr_native.so', handle 55e8b8768830 at 0x7f573ae3eb80>
unicorn: <CDLL '/home/mdl/prog/angr/site-packages/unicorn/lib/libunicorn.so', handle 55e8b850eef0 at 0x7f5739416f38>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x00007f573ab0fbe8>
z3: <CDLL '/home/mdl/prog/angr/site-packages/z3/lib/libz3.so', handle 55e8b7035f70 at 0x55e8b7f47e50>
```

**Comment by dnivra** [comment] 2021-04-21 01:42
Thanks for the bug report and the `nolicense` option! I didn't see that option earlier.

I spent some time looking into this and as suspected, it is a different issue in VEX lifting. The problem is that basic block end address is different according to VEX and unicorn engine. As a result, a memory read that we are not expecting occurs and leading to the crash.

```gdb
(rr) print block_address
$24 = 0x7d754b
(rr) print block_size
$25 = 0x71
(rr) print lift_ret->inst_addrs[0]
$26 = 0x7d754b
(rr) print lift_ret->size
$27 = 0x50
```

The root cause seems to be that the VEX lifter is splitting the block 0x7d754b into two parts:

```python
>>> import angr
>>> p = angr.Project("/usr/local/sicstus4.6.0/bin/sicstus")
>>> p.factory.block(0x7d754b).pp()
0x7d754b:       mov     qword ptr [rsp + 0x10], 0x1001
0x7d7554:       lea     rax, [rsp + 0x10]
0x7d7559:       mov     qword ptr [rsp + 0x18], 0
0x7d7562:       xor     edx, edx
0x7d7564:       mov     qword ptr [rsp + 0x20], 0
0x7d756d:       mov     qword ptr [rsp + 0x28], 0
0x7d7576:       mov     qword ptr [rsp + 0x30], 0
0x7d757f:       mov     qword ptr [rsp + 0x38], 0
0x7d7588:       rol     rdi, 3
0x7d758c:       rol     rdi, 0xd
0x7d7590:       rol     rdi, 0x3d
0x7d7594:       rol     rdi, 0x33
0x7d7598:       xchg    rbx, rbx
>>> p.factory.block(0x7d754b).size
80
>>> p.factory.block(0x7d754b+80).pp()
0x7d759b:       mov     qword ptr [rsp + 8], rdx
0x7d75a0:       mov     rax, qword ptr [rsp + 8]
0x7d75a5:       test    eax, eax
0x7d75a7:       setne   al
0x7d75aa:       test    rbx, rbx
0x7d75ad:       movzx   eax, al
0x7d75b0:       mov     dword ptr [rip + 0x2793ea], eax
0x7d75b6:       jne     0x7d751b
>>> p.factory.block(0x7d754b+80).size
33
>>> hex(80 + 33)
'0x71'
```

@ltfish - could you share your thoughts on this? To me, it does not look like an issue in angr native but in pyvex perhaps.

**Comment by dnivra** [comment] 2021-04-21 02:01
Forgot to add this piece of info. When crash has occurred, the instruction being emulated in unicorn is 0x7d75a0 - the first memory read instruction in the block:

```gdb
(rr) print get_instruction_pointer()
$1 = 0x7d75a0
```

**Comment by rhelmot** [comment] 2021-04-21 05:51
Oh boy! I was wondering when this issue would come up!

From vex:

```
/* "Special" instructions.

   This instruction decoder can decode three special instructions
   which mean nothing natively (are no-ops as far as regs/mem are
   concerned) but have meaning for supporting Valgrind.  A special
   instruction is flagged by the 16-byte preamble 48C1C703 48C1C70D
   48C1C73D 48C1C733 (in the standard interpretation, that means: rolq
   $3, %rdi; rolq $13, %rdi; rolq $61, %rdi; rolq $51, %rdi).
   Following that, one of the following 3 are allowed (standard
   interpretation in parentheses):

      4887DB (xchgq %rbx,%rbx)   %RDX = client_request ( %RAX )
      4887C9 (xchgq %rcx,%rcx)   %RAX = guest_NRADDR
      4887D2 (xchgq %rdx,%rdx)   call-noredir *%RAX
      4887F6 (xchgq %rdi,%rdi)   IR injection

   Any other bytes following the 16-byte preamble are illegal and
   constitute a failure in instruction decoding.  This all assumes
   that the preamble will never occur except in specific code
   fragments designed for Valgrind to catch.

   No prefixes may precede a "Special" instruction.
*/
```

Essentially, the program is using a special noop to communicate something to vex/valgrind. We probably want an option to turn off this feature in vex.

**Comment by drvink** [comment] 2021-04-21 07:05
`sicstus --help` mentions that the `-m` command line option I use in the script is intended for use with Valgrind in some way, so that makes sense (but angr crashes without it, too).

**Comment by rhelmot** [comment] 2021-04-29 21:03
I can't figure out how to reproduce the exact crash described - when I install the program the resulting binary does not contain any `rol` instructions - but I've pushed a branch which attempts to solve the problem. Build vex and pyvex from feat/no_special_instructions and tell me what happens.

**Comment by drvink** [comment] 2021-04-30 14:53
With the feat/no_special_instructions branch, it no longer crashes.

**Comment by rhelmot** [comment] 2021-05-13 00:59
I've merged the branch to master.

**Closed by rhelmot** 2021-05-13 00:59 UTC

**Comment by drvink** [comment] 2021-05-13 01:36
If it's good enough for you it's good enough for me :) Thanks so much!
