### ISSUE TITLE
angr "IndexError : list index out of range" & repr error

### ISSUE THREAD

**Issue by Gyeongje** [angr/angr#625] opened 2017-08-31 02:58 UTC
Hello I am korean.  Please understand that my English is inexperienced.
I am experiencing the same error as using angr.

I installed angr with two installation ways.

First way
1. pip install angr 

Second way 
1. sudo apt-get update
2. sudo apt-get install virtualenvwrapper python2.7-dev build-essential libxml2-dev libxslt1-dev git libffi-dev cmake libreadline-dev libtool debootstrap debian-archive-keyring libglib2.0-dev libpixman-1-dev libqt4-dev graphviz-dev binutils-multiarch nasm libc6:i386 libgcc1:i386 libstdc++6:i386 libtinfo5:i386 zlib1g:i386
3. mkdir ~/.environments
4. sudo find / -name "virtualenvwrapper.sh"
5. export WORKON_HOME="~/.environments"
   source (virtualenvwrapper.sh path) 
  ↑ Insert in ~/.bashrc 
6. source ~/.bashrc
7. mkvirtualenv angr && pip install angr
8. git clone https://github.com/angr/angr-dev.git
   cd angr-dev
   ./setup.sh -i -e angr

In view, angr was installed successfully, but I tried to solve the simple CTF problem,  I got an error..
The picture below is the Defcon 2016 baby-re problem solving.
How do I resolve this error?

![angr error](https://user-images.githubusercontent.com/31283542/29904399-9e7e5550-8e43-11e7-909e-16aa01be9192.png)

**Comment by rhelmot** [comment] 2017-08-31 03:07
That example is currently broken, this is known :( None of us have had the time to fix it yet.

closing this as a duplicate of https://github.com/angr/angr-doc/issues/142

**Closed by rhelmot** 2017-08-31 03:07 UTC

**Comment by Gyeongje** [comment] 2017-09-01 09:24
I'm really sorry, When will the error be resolved..?

**Comment by ltfish** [comment] 2017-09-01 09:25
We usually do not make promises when we fix things in angr, as we are always short of manpower.

**Comment by Gyeongje** [comment] 2017-09-01 09:36
Oh i see, thank you for the reply.
