### ISSUE TITLE
concrete target "bytes can only be stored big-endian" with state.mem

### ISSUE THREAD

**Issue by bannsec** [angr/angr#2579] opened 2021-03-29 17:59 UTC
---

**Describe the bug.**

When using a concrete target and asking angr `state.mem` to lookup a value in what is known to be the target binary (in my test cases, the binary is PIE), it errors with `SimMemoryError: bytes can only be stored big-endian`. However, after I load the same address with `state.memory.load(address, size)`, i can now run `state.mem[address].long` and get the answer back. So it seems that `state.mem` is missing some step in resolution that `state.memory` does. 

**Environment Information.**

```
angr environment report
=============================
Date: 2021-03-29 14:39:30.536643
Running in virtual environment at /home/angr/.virtualenvs/angr
Platform: linux-x86_64
Python version: 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0]
######## angr #########
Python found it in /home/angr/angr-dev/angr/angr
Pip version angr 9.0.gitrolling
Git info:
        Current commit dc7c816f3848d6e39492cb721661a3d191304129 from branch master
        Checked out from remote origin: https://github.com/angr/angr
######## ailment #########
Python found it in /home/angr/angr-dev/ailment/ailment
Pip version ailment 9.0.gitrolling
Git info:
        Current commit 4572efdfdcfbab0f88db9c3fdf8d1b9cbcb2a9c2 from branch master
        Checked out from remote origin: https://github.com/angr/ailment
######## cle #########
Python found it in /home/angr/angr-dev/cle/cle
Pip version cle 9.0.gitrolling
Git info:
        Current commit 7f3263c74a2c038234f5ec6adf8ebb4bf119e868 from branch master
        Checked out from remote origin: https://github.com/angr/cle
######## pyvex #########
Python found it in /home/angr/angr-dev/pyvex/pyvex
Pip version pyvex 9.0.gitrolling
Git info:
        Current commit 38af62047b8a7785feeee6b5f243ad1dbd7db1f6 from branch master
        Checked out from remote origin: https://github.com/angr/pyvex
######## claripy #########
Python found it in /home/angr/angr-dev/claripy/claripy
Pip version claripy 9.0.gitrolling
Git info:
        Current commit db253a680751a9e124a4a091066759348f958183 from branch master
        Checked out from remote origin: https://github.com/angr/claripy
######## archinfo #########
Python found it in /home/angr/angr-dev/archinfo/archinfo
Pip version archinfo 9.0.gitrolling
Git info:
        Current commit f5712a1fe0fbc315c4e9bbcf96582e139f745b33 from branch master
        Checked out from remote origin: https://github.com/angr/archinfo
######## z3 #########
Python found it in /home/angr/.virtualenvs/angr/lib/python3.8/site-packages/z3
Pip version z3-solver 4.8.10.0
Couldn't find git info
######## unicorn #########
Python found it in /home/angr/.virtualenvs/angr/lib/python3.8/site-packages/unicorn
Pip version unicorn 1.0.2rc4
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/angr/angr-dev/angr/angr/lib/angr_native.so', handle 2e76280 at 0x7f20b667b1f0>
unicorn: <CDLL '/home/angr/.virtualenvs/angr/lib/python3.8/site-packages/unicorn/lib/libunicorn.so', handle 22d2c30 at 0x7f20d28cba30>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f20d3580af0>
z3: <CDLL '/home/angr/.virtualenvs/angr/lib/python3.8/site-packages/z3/lib/libz3.so', handle 254e700 at 0x7f20d00932e0>
```

**To Reproduce.**

Just using basic ls for this example.

```python
import angr
import r2pipe
from angr_targets import R2ConcreteTarget
from time import sleep

r2 = r2pipe.open("/bin/ls")
r2.cmd("ood")
r2.cmd("db main") # Or however you want to get it going
r2.cmd("dc")
sleep(1)

r2target = R2ConcreteTarget(r2)
proj = angr.Project("/bin/ls", concrete_target=r2target)

state = proj.factory.entry_state()

main_addr = int(r2.cmd("?v main"), 16)

print("This will error")
try:
    print(state.mem[main_addr].int)
except Exception as e:
    print(e)

print("This will not")
print(state.memory.load(main_addr, 16))
# DEBUG   | 2021-03-29 17:54:55,734 | angr_targets.r2 | R2ConcreteTarget read_memory at 557d95ffadf0 
# Out[17]: <BV128 0xf30f1efa41574156415541544189fc55>

print("Now this will not error")
print(state.mem[main_addr].int)
```

**Additional context.**

**Comment by mauricesvp** [comment] 2021-05-06 19:02
I have actually encountered the same problem without calling `state.mem` myself (but rather by simply running an exploration also using a `concrete_target`).

I think the cause of this is at [storage/memory_mixins/paged_memory/pages/ultra_page.py#L48-L97](https://github.com/angr/angr/blob/32fb4c53fb147ab2e6b5d55aa59bf6ebdd5ecbd6/angr/storage/memory_mixins/paged_memory/pages/ultra_page.py#L48-L97) (one layer above [SimMemoryObject](https://github.com/angr/angr/blob/32fb4c53fb147ab2e6b5d55aa59bf6ebdd5ecbd6/angr/storage/memory_object.py#L13), where the exception is raised).

When using `state.memory.load(addr, size)`, the `symbolic_data` dict is filled with the result: https://github.com/angr/angr/blob/32fb4c53fb147ab2e6b5d55aa59bf6ebdd5ecbd6/angr/storage/memory_mixins/paged_memory/pages/ultra_page.py#L67-L68

Here no exception is raised, as `SimMemoryObject` is called with big-endian endianness.

If you call `state.mem[addr]` now (which uses little-endian), this point will not be reached anymore, because there is a [lookup](https://github.com/angr/angr/blob/32fb4c53fb147ab2e6b5d55aa59bf6ebdd5ecbd6/angr/storage/memory_mixins/paged_memory/pages/ultra_page.py#L343) using the `symbolic_data` dict, which will now return the SimMemoryObject (but would return nothing if `memory.load` wasn't used beforehand).

**Fix**
I am not quite sure what the underlying bug here really is (should the memory load using `state.mem` not use little-endian in the first place? Or is the way the symbolic_data "caching" works not quite right? Or something else entirely, perhaps within the concrete engine?)

Eitherway a (somewhat hacky) solution which fixed my use-case would be to change the `SimMemoryObject` initialization to something like this:
```python
try:
    new_item = SimMemoryObject(new_ast, global_start_addr, endness=endness)
except SimMemoryError:
    endness_tmp = "Iend_BE" if "Iend_LE" else "Iend_LE"
    new_item = SimMemoryObject(new_ast, global_start_addr, endness=endness_tmp)
```

**Comment by degrigis** [comment] 2021-05-22 18:19
This seems to be fixed on master, or, I can't reproduce with the AvatarGDBConcreteTarget (state.mem[address] doesn't throw that Exception for me). 
Can you guys confirm? @mauricesvp @bannsec

Also, @mauricesvp , were you also using the Radare target?

**Comment by mauricesvp** [comment] 2021-05-22 18:58
Hey @degrigis ,
I am using the AvatarGDBConcreteTarget, I have retested my script using the current master and the error is still occuring though.

**Comment by degrigis** [comment] 2021-05-23 18:56
@mauricesvp can you share the script with me? Which version of gdb are you using?

**Comment by mauricesvp** [comment] 2021-05-23 19:16
gdb version is `GNU gdbserver (Ubuntu 9.2-0ubuntu1~20.04) 9.2`
For the script+binary see: [files.zip](https://github.com/angr/angr/files/6528774/files.zip)

**Comment by degrigis** [comment] 2021-05-24 23:02
Ok, I've confirmed the issue.
We have 2 ways of solving this problem: 
1. Make sure that a `ConcreteTarget` implementation always returns memory values that respect the endianness of the loaded binary (this would be a duty of a ConcreteTarget developer).
2. Add more code to the UltraPage's [default_filler](https://github.com/angr/angr/blob/32fb4c53fb147ab2e6b5d55aa59bf6ebdd5ecbd6/angr/storage/memory_mixins/default_filler_mixin.py#L16) to enforce this on the `angr` side. As another user suggested on our Slack, this should be as simple as adding these 4 lines in the default filler code:

```
if self.state.project and self.state.project.concrete_target:
    mem = self.state.project.concrete_target.read_memory(addr, size)
    endness = self.state.project.arch.memory_endness
    bvv = self.state.solver.BVV(mem)
    return bvv if endness == 'Iend_BE' else bvv.reversed
```

I'm actually down for the second solution to relieve users from this issue once for all. Any thoughts @rhelmot @ltfish ?

**Comment by rhelmot** [comment] 2021-05-24 23:06
Second solution seems fine to me.

**Closed** 2021-05-25 21:57 UTC
