### ISSUE TITLE
`pip install angr` fails with unicorn issues

### ISSUE THREAD

**Issue by fmagin** [angr/angr#1933] opened 2020-01-22 14:36 UTC
**Describe the bug.**

`pip install angr` fails because unicorn is trying to compile things and fails

**Environment Information.**
Completely fresh venv on both an current arch linux and an ubuntu system

**To Reproduce.**

Create a fresh venv and run `pip install angr`

```
(tempenv-0dbd325181aa0) ~ $ pip install angr
Collecting angr
  Using cached angr-8.20.1.7.tar.gz (894 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/fmagin/.virtualenvs/tempenv-0dbd325181aa0/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sdu8enqy/angr/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sdu8enqy/angr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-sdu8enqy/angr/pip-egg-info
         cwd: /tmp/pip-install-sdu8enqy/angr/
    Complete output (49 lines):
      ERROR: Command errored out with exit status 1:
       command: /home/fmagin/.virtualenvs/tempenv-0dbd325181aa0/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-5iksds0v/unicorn/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-5iksds0v/unicorn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-u8qv086z
           cwd: /tmp/pip-wheel-5iksds0v/unicorn/
      Complete output (12 lines):
      running bdist_wheel
      running build
      Building C extensions
      cd qemu && \
      ./configure --cc="cc" --extra-cflags="-DUNICORN_HAS_X86 -DUNICORN_HAS_ARM -DUNICORN_HAS_ARMEB -DUNICORN_HAS_M68K -DUNICORN_HAS_ARM64 -DUNICORN_HAS_MIPS -DUNICORN_HAS_MIPSEL -DUNICORN_HAS_MIPS64 -DUNICORN_HAS_MIPS64EL -DUNICORN_HAS_SPARC -fPIC -fvisibility=hidden" --target-list="x86_64-softmmu, arm-softmmu, armeb-softmmu, m68k-softmmu, aarch64-softmmu, mips-softmmu, mipsel-softmmu, mips64-softmmu, mips64el-softmmu, sparc-softmmu,sparc64-softmmu,"
    
      ERROR: Cannot use 'python', Python 2.4 or later is required.
             Note that Python 3 or later is not yet supported.
             Use --python=/path/to/python to specify a supported Python.
    
      make: *** [Makefile:214: qemu/config-host.h-timestamp] Error 1
      error: [Errno 2] No such file or directory: 'libunicorn.so'
      ----------------------------------------
      ERROR: Failed building wheel for unicorn
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/home/fmagin/.virtualenvs/tempenv-0dbd325181aa0/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/lib64/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/home/fmagin/.virtualenvs/tempenv-0dbd325181aa0/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpa8vup8mx', '--quiet', 'unicorn']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-sdu8enqy/angr/setup.py", line 132, in <module>
        setup(
      File "/home/fmagin/.virtualenvs/tempenv-0dbd325181aa0/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/home/fmagin/.virtualenvs/tempenv-0dbd325181aa0/lib/python3.8/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/fmagin/.virtualenvs/tempenv-0dbd325181aa0/lib/python3.8/site-packages/setuptools/dist.py", line 718, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/home/fmagin/.virtualenvs/tempenv-0dbd325181aa0/lib/python3.8/site-packages/pkg_resources/__init__.py", line 781, in resolve
        dist = best[req.key] = env.best_match(
      File "/home/fmagin/.virtualenvs/tempenv-0dbd325181aa0/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1066, in best_match
        return self.obtain(req, installer)
      File "/home/fmagin/.virtualenvs/tempenv-0dbd325181aa0/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1078, in obtain
        return installer(requirement)
      File "/home/fmagin/.virtualenvs/tempenv-0dbd325181aa0/lib/python3.8/site-packages/setuptools/dist.py", line 777, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/home/fmagin/.virtualenvs/tempenv-0dbd325181aa0/lib/python3.8/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/home/fmagin/.virtualenvs/tempenv-0dbd325181aa0/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpa8vup8mx', '--quiet', 'unicorn']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command err
```

**Comment by rhelmot** [comment] 2020-01-22 18:37
this is a duplicate of various unicorn-engine issues which have been fixed but not released. the workaround is `pip install -U 'pip<20'`

**Closed by rhelmot** 2020-01-22 18:37 UTC
